import re

files = {
    'src/components/guards/PartnerTierGuard.tsx': [
        # (ligne_originale, ligne_correcte)
        ("* Guard pour prot\ufffdger les routes selon le niveau sponsor",
         "* Guard pour protéger les routes selon le niveau sponsor"),
        ("* - minimumTier: Niveau minimum requis (ex: silver ou sup\ufffdrieur)",
         "* - minimumTier: Niveau minimum requis (ex: silver ou supérieur)"),
        ("// V\ufffdrifier que l'utilisateur est connect\ufffd",
         "// Vérifier que l'utilisateur est connecté"),
        ("toast.error('Acc\ufffds refus\ufffd', {",
         "toast.error('Accès refusé', {"),
        ("description: 'Vous devez \ufffdtre connect\ufffd pour acc\ufffdder \ufffd cette page.'",
         "description: 'Vous devez être connecté pour accéder à cette page.'"),
        ("// V\ufffdrifier que l'utilisateur est un sponsor",
         "// Vérifier que l'utilisateur est un sponsor"),
        ("description: 'Cette page est r\ufffds\ufffdrv\ufffdée aux sponsors.'",  # maybe
         "description: 'Cette page est réservée aux sponsors.'"),
        ("description: 'Cette page est r\ufffdserv\ufffdée aux sponsors.'",
         "description: 'Cette page est réservée aux sponsors.'"),
        ("// R\ufffdcup\ufffdr\ufffdr le niveau sponsor (depuis le profil ou la base de donn\ufffdées)",
         "// Récupérer le niveau sponsor (depuis le profil ou la base de données)"),
        ("// R\ufffdcup\ufffdrer le niveau sponsor (depuis le profil ou la base de donn\ufffdées)",
         "// Récupérer le niveau sponsor (depuis le profil ou la base de données)"),
        ("// V\ufffdrification du niveau requis exact",
         "// Vérification du niveau requis exact"),
        ("toast.error('Acc\ufffds r\ufffdserv\ufffd', {",
         "toast.error('Accès réservé', {"),
        ("description: customMessage || `Cette fonctionnalit\ufffd est r\ufffdserv\ufffdée aux sponsors ${requiredConfig.displayName}.`,",
         "description: customMessage || `Cette fonctionnalité est réservée aux sponsors ${requiredConfig.displayName}.`,"),
        ("// V\ufffdrification du niveau minimum",
         "// Vérification du niveau minimum"),
        ("// Si le niveau actuel est inf\ufffdrieur au minimum requis",
         "// Si le niveau actuel est inférieur au minimum requis"),
        ("description: customMessage || `Cette fonctionnalit\ufffd n\ufffdcessite au minimum le niveau ${minimumConfig.displayName}.`,",
         "description: customMessage || `Cette fonctionnalité nécessite au minimum le niveau ${minimumConfig.displayName}.`,"),
        ("// V\ufffdrification de quota sp\ufffdcifique (si fourni)",
         "// Vérification de quota spécifique (si fourni)"),
        ("// V\ufffdrifier si le tier a acc\ufffds \ufffd ce quota",
         "// Vérifier si le tier a accès à ce quota"),
        ("title: 'Acc\ufffds restreint',",
         "title: 'Accès restreint',"),
        ("description: customMessage || `Votre niveau ${partnerTier} n'a pas acc\ufffds \ufffd cette fonctionnalit\ufffd. Veuillez upgrader votre compte.`,",
         "description: customMessage || `Votre niveau ${partnerTier} n'a pas accès à cette fonctionnalité. Veuillez upgrader votre compte.`,"),
        ("// Note: La v\ufffdrification de l'utilisation actuelle vs quota max",
         "// Note: La vérification de l'utilisation actuelle vs quota max"),
        ("// n\ufffdcessite une requ\ufffdtte DB et sera impl\ufffdment\ufffdée au niveau du composant",
         "// nécessite une requête DB et sera implémentée au niveau du composant"),
        ("// qui utilise PartnerTierGuard, pas ici pour \ufffdviter les requ\ufffdttes multiples",
         "// qui utilise PartnerTierGuard, pas ici pour éviter les requêtes multiples"),
        ("// Si toutes les v\ufffdrifications passent, afficher le contenu",
         "// Si toutes les vérifications passent, afficher le contenu"),
        ("* Hook pour v\ufffdrifier le niveau sponsor",
         "* Hook pour vérifier le niveau sponsor"),
        ("* Hook pour v\ufffdrifier l'acc\ufffds \ufffd une fonctionnalit\ufffd",
         "* Hook pour vérifier l'accès à une fonctionnalité"),
    ],
    'src/pages/visitor/VisitorBankTransferPage.tsx': [
        ("// G\ufffdn\ufffdrer une r\ufffdférence si elle n'existe pas",
         "// Générer une référence si elle n'existe pas"),
        ("// Sauvegarder la r\ufffdférence",
         "// Sauvegarder la référence"),
        ("toast.error('Veuillez renseigner la r\ufffdférence de votre virement');",
         "toast.error('Veuillez renseigner la référence de votre virement');"),
        ("// Upload du fichier si nouveau fichier s\ufffdlectionn\ufffd",
         "// Upload du fichier si nouveau fichier sélectionné"),
        ("// Mettre \ufffd jour la demande de paiement",
         "// Mettre à jour la demande de paiement"),
        ("toast.success('Justificatif envoy\ufffd avec succ\ufffdés !');",
         "toast.success('Justificatif envoyé avec succès !');"),
        ("toast.success('Justificatif envoy\ufffd avec succ\ufffdès !');",
         "toast.success('Justificatif envoyé avec succès !');"),
        ("toast.info('Votre paiement sera valid\ufffd sous 2-5 jours ouvr\ufffdés');",
         "toast.info('Votre paiement sera validé sous 2-5 jours ouvrés');"),
        ("toast.info('Votre paiement sera valid\ufffd sous 2-5 jours ouvr\ufffdès');",
         "toast.info('Votre paiement sera validé sous 2-5 jours ouvrés');"),
        ("// Recharger les donn\ufffdées",
         "// Recharger les données"),
        ("// V\ufffdrifier le type de fichier",
         "// Vérifier le type de fichier"),
        ("// V\ufffdrifier la taille (max 5MB)",
         "// Vérifier la taille (max 5MB)"),
        ("toast.error('Le fichier ne doit pas d\ufffdpasser 5MB');",
         "toast.error('Le fichier ne doit pas dépasser 5MB');"),
        ("toast.success(`Fichier s\ufffdlectionn\ufffd: ${file.name}`);",
         "toast.success(`Fichier sélectionné: ${file.name}`);"),
        ("toast.success('Copi\ufffd dans le presse-papier');",
         "toast.success('Copié dans le presse-papier');"),
        ("{/* \ufffdtapes */}",
         "{/* Étapes */}"),
        ("? {info}",
         "• {info}"),
        ("{/* Message de confirmation si approuv\ufffd */}",
         "{/* Message de confirmation si approuvé */}"),
    ],
    'scripts/createMissingTables.ts': [
        ("console.log('\ufffd Cr\ufffdation des tables manquantes dans Supabase...');",
         "console.log('🔧 Création des tables manquantes dans Supabase...');"),
        ("console.log('\ufffd Cr\ufffdéation des tables manquantes dans Supabase...');",
         "console.log('🔧 Création des tables manquantes dans Supabase...');"),
    ],
}

# PresentationPage - trop complexe, faire par substitutions simples
presentation_replacements = [
    ("Minist\ufffdre", "Ministère"),
    ("Am\ufffdnagement", "Aménagement"),
    ("D\ufffdveloppement", "Développement"),
    ("F\ufffdd\ufffdration", "Fédération"),
    ("Mat\ufffdériaux", "Matériaux"),
    ("Mat\ufffdrriaux", "Matériaux"),
    ("B\ufffdtiment", "Bâtiment"),
    ("b\ufffdtiment", "bâtiment"),
    ("d\ufffdle\ufffdgu\ufffd", "délégué"),
    ("d\ufffdl\ufffdgu\ufffd", "délégué"),
    ("Organisateur d\ufffdle\ufffdgu\ufffd", "Organisateur délégué"),
    ("?v\ufffdnementiel", "événementiel"),
    ("\ufffdv\ufffdnementiel", "événementiel"),
    ("repr\ufffds\ufffdrnt\ufffdées", "représentées"),
    ("repr\ufffdssent\ufffdées", "représentées"),
    ("repr\ufffdssent\ufffds", "représentés"),
    ("repr\ufffds\ufffdnt\ufffds", "représentés"),
    ("repr\ufffdsentées", "représentées"),
    ("35 000 m\ufffd", "35 000 m²"),
    ("35\u00a0000 m\ufffd", "35\u00a0000 m²"),
    ("SIB \ufffd SIB", "SIB – SIB"),
    ("du B\ufffdtiment \ufffd SIB", "du Bâtiment – SIB"),
    ("20\ufffd\ufffd \ufffdedition", "20ème édition"),
    ("20\ufffd \ufffdedition", "20ème édition"),
    ("20\ufffd ?dition", "20ème édition"),
    ("20\ufffd\ufffd", "20ème"),
    ("c\ufffdl\ufffdebrant", "célébrant"),
    ("d\ufffdroule", "déroule"),
    ("d\ufffdvouera", "se déroulera"),
    ("se d\ufffdroule", "se déroulera"),
    ("se d?roule", "se déroulera"),
    ("Fond\ufffd", "Fondé"),
    ("impos\ufffd", "imposé"),
    ("r\ufffdférence", "référence"),
    ("r\ufffdunit", "réunit"),
    ("m\ufffdme objectif", "même objectif"),
    ("planifi\ufffdées", "planifiées"),
    ("planifi\ufffdes", "planifiées"),
    ("d'exposition, le SIB s'impos", "d'exposition, le SIB s'impose"),
    ("Organis\ufffd par", "Organisé par"),
    ("co-organis\ufffd par", "co-organisé par"),
    ("et des Exportations \ufffd AMDIE", "et des Exportations – AMDIE"),
    ("Construction \ufffd FMC", "Construction – FMC"),
    ("Travaux Publics \ufffd FNBTP", "Travaux Publics – FNBTP"),
    ("gestion d\ufffdl\ufffdgu\ufffdée", "gestion déléguée"),
    ("gestion d\ufffdl\ufffdgu\ufffd", "gestion délégué"),
    ("continuit\ufffd", "continuité"),
    ("qualit\ufffd", "qualité"),
    ("\ufffd travers", "à travers"),
    ("ann\ufffdées", "années"),
    ("port\ufffdée", "portée"),
    ("s'impose aujourd'hui", "s'impose aujourd'hui"),
    ("d\ufffdmonstration", "démonstration"),
    ("conf\ufffdences", "conférences"),
    ("anim\ufffdées", "animées"),
    ("anim\ufffdes", "animées"),
    ("th\ufffdmatiques", "thématiques"),
    ("D\ufffdmonstration", "Démonstration"),
    ("\ufffdvite d'afficher", "évite d'afficher"),
    ("tronqu\ufffd\ufffd", "tronqué"),
    ("tronqu\ufffd", "tronqué"),
    ("Chiffres cl\ufffdés", "Chiffres clés"),
    ("Chiffres cl\ufffds", "Chiffres clés"),
    ("Pr\ufffdésentation", "Présentation"),
    ("Pr\ufffdsentation", "Présentation"),
    ("SIB 2026 \ufffd Pr", "SIB 2026 – Pr"),
    ("R\ufffdduire", "Réduire"),
    ("Entr\ufffdée Gratuite", "Entrée Gratuite"),
    ("Entr\ufffd Gratuite", "Entrée Gratuite"),
    ("L'acc\ufffds au salon est enti\ufffdrement gratuit", "L'accès au salon est entièrement gratuit"),
    ("L'acc\ufffds", "L'accès"),
    ("badge \ufffdlectronique", "badge électronique"),
    ("T\ufffdl\ufffdchargez", "Téléchargez"),
    ("modalit\ufffdées", "modalités"),
    ("modalit\ufffd s", "modalités"),
    # Catch remaining 
    ("1\ufffd\ufffd agence", "1ère agence"),
    ("1\ufffd agence", "1ère agence"),
    ("Au-del\ufffd de sa port", "Au-delà de sa port"),
    ("espace o\ufffd convergent", "espace où convergent"),
    ("r\ufffdférence du secteur", "référence du secteur"),
    ("r\ufffdférence du", "référence du"),
]

# Traiter PartnerTierGuard et VisitorBankTransfer avec remplacements ligne-par-ligne
for path, line_reps in files.items():
    content = open(path, 'r', encoding='utf-8').read()
    for old, new in line_reps:
        if old in content:
            content = content.replace(old, new)
    open(path, 'w', encoding='utf-8').write(content)
    remaining = content.count('\ufffd')
    print(f'{path}: {remaining} U+FFFD restants')

# Traiter PresentationPage
path = 'src/pages/public/PresentationPage.tsx'
content = open(path, 'r', encoding='utf-8').read()
for old, new in presentation_replacements:
    content = content.replace(old, new)
open(path, 'w', encoding='utf-8').write(content)
remaining = content.count('\ufffd')
print(f'{path}: {remaining} U+FFFD restants')
if remaining > 0:
    import re
    for m in re.finditer(r'.{0,40}\ufffd.{0,40}', content):
        print(f'  RESTE: {m.group().encode("ascii","replace").decode()}')
