/** cms_text_content.key → clé data-i18n dans home-sib2026.html */
export const HOME_V4_TEXT_CMS_MAP: Record<string, string> = {
  home_hero_kicker: 'hero.eyebrow',
  home_hero_headline: 'hero.h2',
  home_hero_intro: 'hero.intro',
  home_hero_date: 'hero.date',
  home_hero_location: 'hero.venue',
  home_hero_cta_stand: 'hero.cta_stand',
  home_hero_cta_visitor: 'hero.cta_visitor',
  home_numbers_title: 'numbers.title',
  home_heritage_kicker: 'heritage.kicker',
  home_heritage_title: 'heritage.title',
  home_ecosystem_title: 'ecosystem.title',
  home_ecosystem_desc: 'ecosystem.desc',
  home_ecosystem_cta: 'ecosystem.cta',
  home_legacy_title: 'legacy.title',
  home_legacy_cta: 'legacy.cta',
  home_univers_title: 'univers.title',
  home_talks_subtitle: 'talks.subtitle',
  home_talks_desc: 'talks.desc',
  home_talks_cta: 'talks.cta',
  home_partners_kicker: 'partners.kicker',
  home_partners_title: 'partners.title',
  home_partners_desc: 'partners.desc',
  home_partners_cta: 'partners.cta',
  home_quick_plan: 'quick.plan',
  home_quick_exhibit_title: 'quick.exhibit.title',
  home_quick_exhibit_desc: 'quick.exhibit.desc',
  home_quick_visit_title: 'quick.visit.title',
  home_quick_visit_desc: 'quick.visit.desc',
  home_footer_date: 'footer.date',
  home_cta_reserve: 'cta.reserve',
  home_nav_about: 'nav.about',
  home_nav_exhibit: 'nav.exhibit',
  home_nav_visit: 'nav.visit',
  home_nav_program: 'nav.program',
  home_nav_talks: 'nav.talks',
  home_nav_exhibitors: 'nav.exhibitors',
  home_nav_press: 'nav.press',
  home_nav_infos: 'nav.infos',
  home_footer_about: 'footer.about',
  home_footer_exhibit: 'footer.exhibit',
  home_footer_visit: 'footer.visit',
  home_footer_program: 'footer.program',
  home_footer_newsletter: 'footer.newsletter',
  home_footer_newsletter_desc: 'footer.newsletter.desc',
  home_footer_email_placeholder: 'footer.email.placeholder',
};

export const HOME_V4_STAT_CMS_KEYS = [
  'home_stats_exhibitors',
  'home_stats_visitors',
  'home_stats_countries',
  'home_stats_conferences',
] as const;

export type HomeV4TextDef = {
  key: string;
  label: string;
  placeholder: string;
  category: string;
};

export const HOME_V4_TEXT_DEFINITIONS: HomeV4TextDef[] = [
  { key: 'home_hero_kicker', label: 'Hero — accroche', placeholder: 'SALON INTERNATIONAL DU BÂTIMENT', category: 'Hero' },
  { key: 'home_hero_headline', label: 'Hero — titre principal (HTML autorisé)', placeholder: '40 ANS D\'HÉRITAGE…', category: 'Hero' },
  { key: 'home_hero_intro', label: 'Hero — introduction', placeholder: 'Le plus grand rendez-vous…', category: 'Hero' },
  { key: 'home_hero_date', label: 'Hero — dates', placeholder: '25 › 29 NOVEMBRE 2026', category: 'Hero' },
  { key: 'home_hero_location', label: 'Hero — lieu (HTML autorisé)', placeholder: 'PARC D\'EXPOSITION…', category: 'Hero' },
  { key: 'home_hero_cta_stand', label: 'Hero — bouton exposant', placeholder: 'RÉSERVER UN STAND →', category: 'Hero' },
  { key: 'home_hero_cta_visit', label: 'Hero — bouton visiteur', placeholder: 'PRÉ-ENREGISTREMENT VISITEUR →', category: 'Hero' },
  { key: 'home_cta_reserve', label: 'Header — réserver un stand', placeholder: 'RÉSERVER UN STAND', category: 'Header' },
  { key: 'home_numbers_title', label: 'Section chiffres — titre', placeholder: 'SIB EN CHIFFRES', category: 'Chiffres' },
  { key: 'home_stats_exhibitors', label: 'Chiffre — exposants', placeholder: '500+', category: 'Chiffres' },
  { key: 'home_stats_visitors', label: 'Chiffre — visiteurs', placeholder: '200 000+', category: 'Chiffres' },
  { key: 'home_stats_countries', label: 'Chiffre — pays', placeholder: '50+', category: 'Chiffres' },
  { key: 'home_stats_conferences', label: 'Chiffre — ans d\'histoire', placeholder: '40', category: 'Chiffres' },
  { key: 'home_heritage_kicker', label: 'Héritage — accroche', placeholder: 'QUATRE DÉCENNIES…', category: 'Héritage' },
  { key: 'home_heritage_title', label: 'Héritage — titre (HTML)', placeholder: '<span>40 ANS</span> DE CONSTRUCTION', category: 'Héritage' },
  { key: 'home_ecosystem_title', label: 'Écosystème — titre (HTML)', placeholder: 'L\'ÉCOSYSTÈME<br>DU BÂTIMENT', category: 'Écosystème' },
  { key: 'home_ecosystem_desc', label: 'Écosystème — description', placeholder: 'Le SIB réunit tous les acteurs…', category: 'Écosystème' },
  { key: 'home_ecosystem_cta', label: 'Écosystème — bouton (HTML)', placeholder: 'DÉCOUVRIR TOUS<br>LES UNIVERS →', category: 'Écosystème' },
  { key: 'home_legacy_title', label: 'Legacy — titre (HTML)', placeholder: '<span>40 ANS</span><br>AUX CÔTÉS…', category: 'Legacy' },
  { key: 'home_legacy_cta', label: 'Legacy — bouton', placeholder: 'DÉCOUVRIR LEUR HISTOIRE →', category: 'Legacy' },
  { key: 'home_univers_title', label: 'Univers — titre', placeholder: 'LES UNIVERS DU SIB', category: 'Univers' },
  { key: 'home_talks_subtitle', label: 'SIB Talks — sous-titre', placeholder: 'DÉBATS, CONFÉRENCES…', category: 'SIB Talks' },
  { key: 'home_talks_desc', label: 'SIB Talks — description', placeholder: 'Des experts internationaux…', category: 'SIB Talks' },
  { key: 'home_talks_cta', label: 'SIB Talks — bouton', placeholder: 'DÉCOUVRIR LE PROGRAMME →', category: 'SIB Talks' },
  { key: 'home_partners_kicker', label: 'Partenaires — accroche', placeholder: 'INSTITUTIONS, FÉDÉRATIONS…', category: 'Partenaires' },
  { key: 'home_partners_title', label: 'Partenaires — titre (HTML)', placeholder: 'ORGANISATEURS & <span>SPONSOR…', category: 'Partenaires' },
  { key: 'home_partners_desc', label: 'Partenaires — description', placeholder: 'Un salon porté par…', category: 'Partenaires' },
  { key: 'home_partners_cta', label: 'Partenaires — bouton', placeholder: 'VOIR TOUS LES EXPOSANTS →', category: 'Partenaires' },
  { key: 'home_quick_plan', label: 'Lien rapide — plan (HTML)', placeholder: 'PLAN INTERACTIF<br>DU SALON', category: 'Liens rapides' },
  { key: 'home_quick_exhibit_title', label: 'Lien rapide — exposer titre', placeholder: 'EXPOSER AU SIB 2026', category: 'Liens rapides' },
  { key: 'home_quick_exhibit_desc', label: 'Lien rapide — exposer desc', placeholder: 'BOOSTEZ VOTRE VISIBILITÉ', category: 'Liens rapides' },
  { key: 'home_quick_visit_title', label: 'Lien rapide — visiter titre', placeholder: 'VISITER LE SALON', category: 'Liens rapides' },
  { key: 'home_quick_visit_desc', label: 'Lien rapide — visiter desc (HTML)', placeholder: 'PRÉ-ENREGISTREZ-VOUS<br>DÈS MAINTENANT', category: 'Liens rapides' },
  { key: 'home_footer_date', label: 'Footer iframe — dates & lieu (HTML)', placeholder: '▣ 25 › 29 NOVEMBRE 2026…', category: 'Footer iframe' },
  { key: 'home_nav_about', label: 'Nav — À propos', placeholder: 'À PROPOS', category: 'Navigation iframe' },
  { key: 'home_nav_exhibit', label: 'Nav — Exposer', placeholder: 'EXPOSER', category: 'Navigation iframe' },
  { key: 'home_nav_visit', label: 'Nav — Visiter', placeholder: 'VISITER', category: 'Navigation iframe' },
  { key: 'home_nav_program', label: 'Nav — Programme', placeholder: 'PROGRAMME', category: 'Navigation iframe' },
  { key: 'home_nav_talks', label: 'Nav — SIB Talks', placeholder: 'SIB TALKS', category: 'Navigation iframe' },
  { key: 'home_nav_exhibitors', label: 'Nav — Exposants', placeholder: 'EXPOSANTS', category: 'Navigation iframe' },
  { key: 'home_nav_press', label: 'Nav — Presse', placeholder: 'PRESSE', category: 'Navigation iframe' },
  { key: 'home_nav_infos', label: 'Nav — Infos pratiques', placeholder: 'INFOS PRATIQUES', category: 'Navigation iframe' },
  { key: 'home_footer_about', label: 'Footer iframe — À propos', placeholder: 'À PROPOS', category: 'Footer iframe' },
  { key: 'home_footer_exhibit', label: 'Footer iframe — Exposer', placeholder: 'EXPOSER', category: 'Footer iframe' },
  { key: 'home_footer_visit', label: 'Footer iframe — Visiter', placeholder: 'VISITER', category: 'Footer iframe' },
  { key: 'home_footer_program', label: 'Footer iframe — Programme', placeholder: 'PROGRAMME', category: 'Footer iframe' },
  { key: 'home_footer_newsletter', label: 'Footer iframe — Newsletter titre', placeholder: 'NEWSLETTER', category: 'Footer iframe' },
  { key: 'home_footer_newsletter_desc', label: 'Footer iframe — Newsletter desc', placeholder: 'Restez informé…', category: 'Footer iframe' },
  { key: 'home_footer_email_placeholder', label: 'Footer iframe — Email placeholder', placeholder: 'Votre email', category: 'Footer iframe' },
];

export const HOME_V4_TEXT_CMS_KEYS = [
  ...HOME_V4_TEXT_DEFINITIONS.map((d) => d.key).filter((k) => !HOME_V4_STAT_CMS_KEYS.includes(k as typeof HOME_V4_STAT_CMS_KEYS[number])),
];
