export const LAB_ROUTES = {
  ROOT: '/lab',
  LOGIN: '/lab/login',
  CLIENT_LOGIN: '/lab/client-login',
  REQUEST_FORM: '/lab/request-form',
  ADMIN_DASHBOARD: '/lab/admin/dashboard',
  ADMIN_REQUESTS: '/lab/admin/requests',
  ADMIN_REQUEST: '/lab/admin/requests/:id',
  ADMIN_QUOTES: '/lab/admin/quotes',
  ADMIN_QUOTE: '/lab/admin/quotes/:id',
  ADMIN_SUPPLIERS: '/lab/admin/suppliers',
  ADMIN_SUPPLIER: '/lab/admin/suppliers/:id',
  ADMIN_CONSULTATIONS: '/lab/admin/consultations',
  ADMIN_CONSULTATION: '/lab/admin/consultations/:id',
  ADMIN_ORDERS: '/lab/admin/orders',
  ADMIN_ORDER: '/lab/admin/orders/:id',
  ADMIN_SAMPLES: '/lab/admin/samples',
  ADMIN_SAMPLE: '/lab/admin/samples/:id',
  ADMIN_ANALYSES: '/lab/admin/analyses',
  ADMIN_RESULTS: '/lab/admin/results',
  ADMIN_VALIDATIONS: '/lab/admin/validations',
  ADMIN_REPORTS: '/lab/admin/reports',
  ADMIN_REPORT_TEMPLATES: '/lab/admin/report-templates',
  ADMIN_CLIENTS: '/lab/admin/clients',
  ADMIN_USERS: '/lab/admin/users',
  ADMIN_TASKS: '/lab/admin/tasks',
  ADMIN_INVOICES: '/lab/admin/invoices',
  ADMIN_PAYMENTS: '/lab/admin/payments',
  ADMIN_SETTINGS: '/lab/admin/settings',
  ADMIN_AUDIT: '/lab/admin/audit',
  ADMIN_BACKUPS: '/lab/admin/backups',
  ADMIN_DEADLINES: '/lab/admin/deadlines',
  ADMIN_SUPPLIER_INVOICES: '/lab/admin/supplier-invoices',
  ADMIN_EMAILS: '/lab/admin/emails',
  ADMIN_MFA: '/lab/admin/mfa',
  ADMIN_INBOX: '/lab/admin/inbox',
  ADMIN_CALLS: '/lab/admin/calls',
  ADMIN_REGULATION: '/lab/admin/regulatory',
  ADMIN_REGULATORY: '/lab/admin/regulatory',
  CLIENT_DASHBOARD: '/lab/client/dashboard',
  CLIENT_REQUESTS: '/lab/client/requests',
  CLIENT_REQUEST: '/lab/client/requests/:id',
  CLIENT_QUOTES: '/lab/client/quotes',
  CLIENT_REPORTS: '/lab/client/reports',
  CLIENT_INVOICES: '/lab/client/invoices',
  CLIENT_PROFILE: '/lab/client/profile',
  SUPPLIER_OFFER: '/lab/supplier-offer/:token',
  QUOTE_SURVEY: '/lab/quote-survey/:token',
} as const;

export function isLabPath(pathname: string): boolean {
  return pathname === '/lab' || pathname.startsWith('/lab/');
}
