"""
Script de traduction arabe - Phase 2 (groupes restants)
"""
import re

AR2 = {
    # SUB / VISITOR LANDING PAGE
    'sub.hero.badge': 'في قلب البناء العالمي',
    'sub.hero.title1': 'زيارة المعرض الدولي',
    'sub.hero.titleHighlight1': 'للبناء',
    'sub.hero.title2': 'و',
    'sub.hero.titleHighlight2': 'التشييد',
    'sub.hero.title3': 'ونظامه البيئي',
    'sub.hero.desc': 'من 25 إلى 29 نوفمبر 2026 في الجديدة - المغرب، يفتح معرض SIB أبوابه لاكتشاف ولقاء والتعاون مع كبار الفاعلين في قطاع البناء العالمي.',
    'sub.hero.badgeBtn': 'أطلب شارتي كزائر',
    'sub.hero.vipBtn': 'تذكرة VIP',
    'sub.stat1.label': 'عارض دولي',
    'sub.stat2.label': 'زائر مهني',
    'sub.stat3.label': 'دولة ممثلة',
    'sub.stat4.label': 'مؤتمرات وورشات',
    'sub.whySection.label': 'لماذا تزور؟',
    'sub.whySection.title': 'لماذا تزور SIB؟',
    'sub.whySection.subtitle': 'تجربة غامرة في قلب الابتكار',
    'sub.whySection.worldEvent': 'حدث عالمي',
    'sub.whySection.worldEventDesc': 'أكبر معرض بناء في المنطقة',
    'sub.why1': 'استكشف أحدث الابتكارات في البناء الذكي والاتصال والبنية التحتية المستدامة.',
    'sub.why2': 'احضر 20 مؤتمراً وورشة عمل تقنية يقدمها خبراء من رواد العالم.',
    'sub.why3': 'استفد من جلسات التواصل المستهدف لبناء علاقات مهنية.',
    'sub.why4': 'اكتشف التدريبات والمهن الجديدة في القطاع.',
    'sub.why5': 'استمتع بتجربة استثنائية فريدة.',
    'sub.pav1.title': 'الهيئات المؤسسية',
    'sub.pav1.desc': 'الاستراتيجيات العالمية والتعاون الدولي',
    'sub.pav2.title': 'صناعة البناء',
    'sub.pav2.desc': 'المعدات والرقمنة والاستدامة',
    'sub.pav3.title': 'الإدارة والاستغلال',
    'sub.pav3.desc': 'الابتكارات والخبرات والممرات',
    'sub.pav4.title': 'الأكاديمي والتكوين',
    'sub.pav4.desc': 'الوظائف والتكوينات والمحاكاة',
    'sub.pav5.title': 'متحف المباني',
    'sub.pav5.desc': 'التراث والفن والذاكرة والابتكار الثقافي',
    'sub.pavSection.label': 'اكتشف الأكوان الخمسة لـ SIB',
    'sub.pavSection.title': 'زوار، استكشفوا أجنحتنا',
    'sub.needInfo': 'تحتاج معلومات؟',
    'sub.contactUs': 'اتصل بنا',
    'sub.plans.label': 'باقات الزوار',
    'sub.plans.title': 'اختر الباقة التي تناسبك',
    'sub.plans.subtitle': 'عظّم تجربتك في SIB',
    'sub.plans.visitors': 'الزوار',
    'sub.plans.exhibitors': 'العارضون',
    'sub.plans.partners': 'الرعاة',
    'sub.plans.features': 'المزايا',
    'sub.plans.benefits': 'الفوائد',
    'sub.plans.onQuote': 'على طلب',
    'sub.plans.free': 'مجاني',
    'sub.plans.customPlan': 'تحتاج باقة مخصصة؟',
    'sub.plans.customPlanDesc': 'اتصل بنا',
    'sub.how.title': 'كيف يعمل ذلك؟',
    'sub.how.step1Title': 'اختيار الباقة',
    'sub.how.step1Desc': 'حدد الباقة التي تناسب احتياجاتك.',
    'sub.how.step2Title': 'دفع آمن',
    'sub.how.step2Desc': 'دفع عبر الإنترنت أو عبر مسؤول المبيعات.',
    'sub.how.step3Title': 'وصول فوري',
    'sub.how.step3Desc': 'وصول فوري للوحة التحكم وجميع مزايا عرضك.',
    'sub.info.label': 'نظّم زيارتك!',
    'sub.info.title': 'معلومات عملية',
    'sub.info.venue': 'المكان',
    'sub.info.venueAddr': 'مركز المعارض الجديدة',
    'sub.info.dates': 'التواريخ',
    'sub.info.datesVal': '25-29 نوفمبر 2026',
    'sub.info.hours': 'التوقيت',
    'sub.info.hoursVal': '9:00 صباحاً حتى 7:00 مساءً',
    'sub.info.entry': 'الدخول',
    'sub.info.entryVal': 'بشارة اسمية',
    'sub.info.contact': 'التواصل مع المنظمين',
    'sub.info.contactOrg': 'URBACOM',
    'sub.info.contactAddr': '63، مبنى B، الدار البيضاء 20510',
    'sub.info.contactBtn': 'اتصل بنا',
    'sub.faq.title': 'الأسئلة الشائعة',
    'sub.faq.q1': 'هل يمكنني تغيير باقتي؟',
    'sub.faq.a1': 'نعم، يمكنك تطوير عرضك في أي وقت.',
    'sub.faq.q2': 'ما هو وقت التفعيل؟',
    'sub.faq.a2': 'بمجرد التحقق من الدفع، يتم تفعيل وصولك في غضون 24 ساعة.',
    'sub.faq.q3': 'هل هناك فوترة متكررة؟',
    'sub.faq.a3': 'لا، إلا إذا كان مذكوراً غير ذلك. الباقات لمرة واحدة لمعرض 2026.',
    'sub.faq.q4': 'كيف يمكنني التواصل مع الدعم؟',
    'sub.faq.a4': 'تواصل مع فريقنا عبر النموذج أو البريد الإلكتروني.',
    'sub.visitorFree.name': 'زائر مجاني',
    'sub.visitorFree.desc': 'الوصول الأساسي للمعرض',
    'sub.visitorPro.name': 'زائر Pro',
    'sub.visitorPro.desc': 'وصول موسّع مع مزايا إضافية',
    'sub.visitorVIP.name': 'زائر VIP',
    'sub.visitorVIP.desc': 'وصول حصري وخدمات متميزة',
    'sub.cta.title': 'انضم إلى المعرض',
    'sub.cta.subtitle': 'سجّل الآن وكن جزءاً من SIB 2026',
    'sub.cta.button': 'التسجيل',
    # PAGES
    'pages.exhibitors.title': 'العارضون',
    'pages.exhibitors.description': 'اكتشف الشركات والمنظمات المشاركة في SIB 2026',
    'pages.exhibitors.search': 'البحث عن عارض',
    'pages.exhibitors.filter_category': 'الفئة',
    'pages.exhibitors.all_categories': 'جميع الفئات',
    'pages.exhibitors.category_institutional': 'مؤسسي',
    'pages.exhibitors.category_port_industry': 'صناعة البناء',
    'pages.exhibitors.category_operations': 'الاستغلال والإدارة',
    'pages.exhibitors.category_academic': 'الأكاديمي والتكوين',
    'pages.exhibitors.category_technology': 'التكنولوجيا',
    'pages.exhibitors.category_automation': 'الأتمتة',
    'pages.exhibitors.category_equipment': 'المعدات',
    'pages.exhibitors.featured': 'مميز',
    'pages.exhibitors.verified': 'معتمد',
    'pages.exhibitors.contact': 'تواصل',
    'pages.exhibitors.view_profile': 'عرض الملف',
    'pages.exhibitors.no_results': 'لا يوجد عارض',
    'pages.partners.title': 'الرعاة',
    'pages.partners.description': 'المنظمات الداعمة لـ SIB 2026',
    'pages.partners.search': 'البحث عن راعي',
    'pages.partners.filter_tier': 'نوع الشراكة',
    'pages.partners.tier_organizer': 'منظم',
    'pages.partners.tier_co_organizer': 'شريك منظم',
    'pages.partners.tier_official_sponsor': 'راعٍ رسمي',
    'pages.partners.tier_delegated_organizer': 'منظم مفوّض',
    'pages.partners.tier_partner': 'راعٍ',
    'pages.partners.tier_press_partner': 'شريك إعلامي',
    'pages.partners.view_details': 'عرض التفاصيل',
    'pages.partners.no_results': 'لا يوجد راعٍ',
    'pages.partners.category_education': 'التعليم والتكوين',
    'pages.partners.try_modify': 'حاول تعديل الفلاتر',
    'pages.partners.reset_filters': 'إعادة تعيين الفلاتر',
    'pages.events.title': 'الأحداث',
    'pages.events.description': 'المؤتمرات وورشات العمل وأنشطة المعرض',
    'pages.events.search': 'البحث عن حدث',
    'pages.events.filter_date': 'التاريخ',
    'pages.events.date': 'التاريخ',
    'pages.events.time': 'الوقت',
    'pages.events.location': 'المكان',
    'pages.events.capacity': 'المقاعد المتاحة',
    'pages.events.register': 'التسجيل',
    'pages.events.registered': 'مسجل',
    'pages.events.no_results': 'لا يوجد حدث',
    'pages.events.scientific_programme': 'البرنامج العلمي',
    'pages.events.type_officiel': 'رسمي',
    'pages.events.type_panel': 'نقاش',
    'pages.events.type_table_ronde': 'طاولة مستديرة',
    'pages.events.type_ted_talk': 'Ted Talk',
    'pages.events.type_atelier': 'ورشة عمل',
    'pages.events.type_pause': 'استراحة',
    'pages.events.type_concours': 'مسابقة',
    'pages.events.type_cloture': 'ختام',
    'pages.events.strategic_reflection': 'فضاء للتفكير الاستراتيجي يجمع المسؤولين والفاعلين الكبار',
    'pages.events.info_dates_location': '{dates} · {location}',
    'pages.news.title': 'الأخبار',
    'pages.news.description': 'آخر أخبار المعرض والقطاع',
    'pages.news.search': 'البحث في الأخبار',
    'pages.news.read_more': 'اقرأ المزيد',
    'pages.news.published': 'نشر في',
    'pages.news.no_results': 'لا توجد أخبار',
    'pages.accommodation.title': 'الإقامة',
    'pages.accommodation.description': 'الفنادق الموصى بها لزوار SIB',
    'pages.accommodation.partner_hotels': 'الفنادق الشريكة',
    'pages.accommodation.book': 'احجز',
    'pages.accommodation.stars': 'نجوم',
    'pages.accommodation.per_night': 'لكل ليلة',
    'pages.accommodation.from': 'ابتداءً من',
    'pages.accommodation.distance': 'المسافة من المعرض',
    'pages.accommodation.no_results': 'لا توجد فنادق',
    'pages.media.title': 'الإعلام',
    'pages.media.description': 'محتوى إعلامي حصري',
    'pages.media.all': 'الكل',
    'pages.media.webinars': 'الندوات',
    'pages.media.podcasts': 'البودكاست',
    'pages.media.videos': 'الفيديوهات',
    'pages.media.no_results': 'لا يوجد محتوى',
    'pages.speakers.title': 'المتحدثون',
    'pages.speakers.description': 'خبراء وقادة الصناعة في SIB 2026',
    'pages.speakers.search': 'البحث عن متحدث',
    'pages.speakers.no_results': 'لا يوجد متحدث',
    'pages.plan.title': 'مخطط القاعة',
    'pages.plan.description': 'تصفح مخطط المعرض',
    'pages.networking.title': 'التواصل',
    'pages.networking.description': 'تواصل مع المهنيين',
    'pages.contact.title': 'اتصل بنا',
    'pages.contact.description': 'نحن هنا للإجابة على استفساراتك',
    # MARKETING
    'marketing.dashboard_title': 'لوحة التحكم التسويقي',
    'marketing.welcome': 'مرحباً في فضاء التسويق الخاص بك',
    'marketing.overview': 'نظرة عامة',
    'marketing.campaigns': 'الحملات',
    'marketing.analytics': 'التحليلات',
    'marketing.reports': 'التقارير',
    'marketing.media_library': 'مكتبة الوسائط',
    'marketing.featured_badges': 'الشارات المميزة',
    'marketing.create_campaign': 'إنشاء حملة',
    'marketing.campaign_title': 'عنوان الحملة',
    'marketing.campaign_description': 'الوصف',
    'marketing.campaign_start_date': 'تاريخ البداية',
    'marketing.campaign_end_date': 'تاريخ النهاية',
    'marketing.campaign_budget': 'الميزانية',
    'marketing.campaign_status': 'الحالة',
    'marketing.active': 'نشط',
    'marketing.inactive': 'غير نشط',
    'marketing.draft': 'مسودة',
    'marketing.published': 'منشور',
    'marketing.pending': 'قيد الانتظار',
    'marketing.statistics': 'الإحصائيات',
    'marketing.views': 'المشاهدات',
    'marketing.clicks': 'النقرات',
    'marketing.conversions': 'التحويلات',
    'marketing.engagement': 'التفاعل',
    'marketing.reach': 'الوصول',
    'marketing.impressions': 'الانطباعات',
    'marketing.ctr': 'معدل النقر',
    'marketing.cpc': 'تكلفة النقرة',
    'marketing.roi': 'العائد على الاستثمار',
    'marketing.filter_status': 'تصفية حسب الحالة',
    'marketing.filter_date': 'تصفية حسب التاريخ',
    'marketing.sort': 'ترتيب',
    'marketing.sort_newest': 'الأحدث',
    'marketing.sort_oldest': 'الأقدم',
    'marketing.action_edit': 'تعديل',
    'marketing.action_delete': 'حذف',
    'marketing.action_publish': 'نشر',
    'marketing.action_duplicate': 'تكرار',
    'marketing.badge': 'مركز التحكم التسويقي',
    'marketing.title': 'مركز المحتوى',
    'marketing.subtitle': 'إدارة الاستراتيجية التسويقية',
    'marketing.btn_new_content': 'محتوى جديد',
    'marketing.tabs.explore': 'استكشاف',
    'marketing.tabs.media_library': 'مكتبة الوسائط',
    'marketing.tabs.articles_news': 'المقالات والأخبار',
    'marketing.stats.total_media': 'إجمالي الوسائط',
    'marketing.stats.total': 'المجموع',
    'marketing.stats.webinars': 'الندوات',
    'marketing.stats.podcasts': 'البودكاست',
    'marketing.stats.capsules': 'الكبسولات',
    'marketing.stats.articles': 'المقالات',
    'marketing.stats.live': 'البث المباشر',
    'marketing.stats.total_content': 'المحتوى الكلي',
    'marketing.filter_type': 'النوع',
    'marketing.filter_all': 'الكل',
    'marketing.no_content': 'لا يوجد محتوى',
    'marketing.content_type': 'نوع المحتوى',
    'marketing.create_content': 'إنشاء محتوى',
    'marketing.edit_content': 'تعديل المحتوى',
    'marketing.delete_content': 'حذف المحتوى',
    'marketing.publish_content': 'نشر المحتوى',
    'marketing.schedule_content': 'جدولة المحتوى',
    'marketing.audience': 'الجمهور',
    'marketing.target_audience': 'الجمهور المستهدف',
    'marketing.channel': 'القناة',
    'marketing.channels': 'القنوات',
    'marketing.email_marketing': 'التسويق بالبريد الإلكتروني',
    'marketing.social_media': 'وسائل التواصل الاجتماعي',
    'marketing.seo': 'تحسين محركات البحث',
    'marketing.load_error': 'خطأ في التحميل',
    # PARTNER SUPPORT
    'partSupport.title': 'دعم الشركاء',
    'partSupport.subtitle': 'الدعم الخاص بالشركاء',
    'partSupport.contact_title': 'تواصل مع الدعم',
    'partSupport.contact_subtitle': 'فريقنا متاح لمساعدتك',
    'partSupport.email_label': 'البريد الإلكتروني',
    'partSupport.phone_label': 'الهاتف',
    'partSupport.hours_label': 'ساعات العمل',
    'partSupport.chat_label': 'المحادثة المباشرة',
    'partSupport.faq_title': 'الأسئلة الشائعة',
    'partSupport.faq_subtitle': 'الإجابات على أبرز الأسئلة',
    'partSupport.q1': 'كيف أحصل على شارتي كشريك؟',
    'partSupport.a1': 'بعد اعتماد تسجيلك، ستتلقى شارتك بالبريد الإلكتروني.',
    'partSupport.q2': 'كيف أدير ملفي الشخصي؟',
    'partSupport.a2': 'من لوحة التحكم، اذهب إلى قسم الملف الشخصي.',
    'partSupport.q3': 'كيف أعرض خدماتي؟',
    'partSupport.a3': 'في قسم الموقع المصغر، يمكنك إضافة جميع خدماتك.',
    'partSupport.docs_title': 'الوثائق',
    'partSupport.docs_subtitle': 'دليل الشركاء والموارد',
    'partSupport.download_guide': 'تنزيل الدليل',
    'partSupport.visit_faq': 'عرض الأسئلة الشائعة',
    'partSupport.resources': 'الموارد',
    'partSupport.contact_btn': 'اتصل بالدعم',
    'partSupport.open_ticket': 'فتح تذكرة',
    'partSupport.ticket_created': 'تم إنشاء التذكرة',
    'partSupport.ticket_error': 'خطأ في إنشاء التذكرة',
    'partSupport.feedback': 'ملاحظات',
    'partSupport.helpful': 'هل كانت هذه المساعدة مفيدة؟',
    'partSupport.yes': 'نعم',
    'partSupport.no': 'لا',
    # UPGRADE
    'upgrade.title': 'ترقية الباقة',
    'upgrade.subtitle': 'اختر الباقة التي تناسبك',
    'upgrade.current_plan': 'باقتك الحالية',
    'upgrade.upgrade_to': 'الترقية إلى',
    'upgrade.features': 'المزايا',
    'upgrade.benefits': 'الفوائد',
    'upgrade.price': 'السعر',
    'upgrade.per_month': 'لكل شهر',
    'upgrade.per_year': 'لكل سنة',
    'upgrade.billed_monthly': 'فوترة شهرية',
    'upgrade.billed_yearly': 'فوترة سنوية',
    'upgrade.save': 'وفّر',
    'upgrade.recommended': 'موصى به',
    'upgrade.popular': 'الأكثر شعبية',
    'upgrade.basic': 'أساسي',
    'upgrade.pro': 'Pro',
    'upgrade.enterprise': 'مؤسسة',
    'upgrade.free': 'مجاني',
    'upgrade.contact_sales': 'اتصل بالمبيعات',
    'upgrade.get_started': 'ابدأ',
    'upgrade.upgrade_btn': 'ترقية',
    'upgrade.cancel': 'إلغاء',
    'upgrade.confirm': 'تأكيد الترقية',
    'upgrade.success': 'تم الترقية بنجاح',
    'upgrade.error': 'خطأ في الترقية',
    'upgrade.includes': 'يشمل',
    'upgrade.everything_in': 'كل ما في',
    'upgrade.plus': 'بالإضافة إلى',
    'upgrade.unlimited': 'غير محدود',
    'upgrade.limited': 'محدود',
    'upgrade.compare': 'مقارنة الباقات',
    'upgrade.faq': 'الأسئلة الشائعة',
    'upgrade.contact_support': 'اتصل بالدعم',
    'upgrade.downgrade': 'خفض الباقة',
    'upgrade.cancel_subscription': 'إلغاء الاشتراك',
    'upgrade.renew': 'تجديد',
    'upgrade.expires': 'ينتهي في',
    'upgrade.auto_renew': 'تجديد تلقائي',
    # VISITOR
    'visitor.about': 'عن الزائر',
    'visitor.appointments': 'المواعيد',
    'visitor.badge': 'الشارة',
    'visitor.bio': 'نبذة',
    'visitor.calendar': 'التقويم',
    'visitor.company': 'الشركة',
    'visitor.connect': 'تواصل',
    'visitor.connections': 'الاتصالات',
    'visitor.contact': 'اتصل',
    'visitor.country': 'البلد',
    'visitor.dashboard': 'لوحة التحكم',
    'visitor.details': 'التفاصيل',
    'visitor.email': 'البريد الإلكتروني',
    'visitor.empty': 'لا يوجد زوار',
    'visitor.events': 'الأحداث',
    'visitor.favorites': 'المفضلة',
    'visitor.filter': 'تصفية',
    'visitor.interests': 'الاهتمامات',
    'visitor.language': 'اللغة',
    'visitor.load_error': 'خطأ في التحميل',
    'visitor.messages': 'الرسائل',
    'visitor.name': 'الاسم',
    'visitor.networking': 'التواصل',
    'visitor.newsletter': 'النشرة الإخبارية',
    'visitor.not_found': 'الزائر غير موجود',
    'visitor.notifications': 'الإشعارات',
    'visitor.phone': 'الهاتف',
    'visitor.plan': 'الخطة',
    'visitor.position': 'المنصب',
    'visitor.privacy': 'الخصوصية',
    'visitor.profile': 'الملف الشخصي',
    'visitor.qr_code': 'رمز QR',
    'visitor.registered_events': 'الأحداث المسجلة',
    'visitor.save': 'حفظ',
    'visitor.save_error': 'خطأ في الحفظ',
    'visitor.saved': 'تم الحفظ',
    'visitor.scan_badge': 'مسح الشارة',
    'visitor.schedule': 'الجدول',
    'visitor.search': 'بحث',
    'visitor.sector': 'القطاع',
    'visitor.sectors': 'القطاعات',
    'visitor.settings': 'الإعدادات',
    'visitor.show_profile': 'إظهار الملف',
    'visitor.status': 'الحالة',
    'visitor.subtitle': 'ملف الزائر',
    'visitor.title': 'الزائر',
    'visitor.type': 'النوع',
    'visitor.update_error': 'خطأ في التحديث',
    'visitor.visibility': 'الظهور',
    'visitor.website': 'الموقع الإلكتروني',
    'visitor.welcome': 'مرحباً',
    # SPONSORS / MENU
    'sponsors.devenir': 'أصبح راعياً',
    'sponsors.devenir_desc': 'فرص الرعاية',
    'sponsors.annuaire': 'دليل الرعاة',
    'sponsors.annuaire_desc': 'رعاة SIB 2026',
    'menu.pavilions_desc': 'استكشف أجنحة المعرض',
    'menu.events_desc': 'المؤتمرات وورشات العمل',
    'menu.news_desc': 'آخر الأخبار',
    'menu.subscriptions_desc': 'الباقات والاشتراكات',
    'menu.accommodation_desc': 'الفنادق الشريكة وأسعار تفضيلية',
    'event.about': 'حول SIB',
    'event.about_desc': 'اكتشف المعرض الدولي',
    'event.program_desc': 'المؤتمرات والمتحدثون',
    'event.pavilions': 'الأجنحة',
    'event.pavilions_desc': 'المناطق الموضوعية والعارضون',
    'event.news': 'الأخبار',
    'event.news_desc': 'آخر الأخبار',
    'event.prepare_visit': 'تحضير زيارتي',
    'event.prepare_desc': 'الإقامة والوصول والمخطط',
    'participate.visitors': 'الزوار',
    'participate.visitors_desc': 'تسجيل مجاني أو تذكرة VIP',
    'participate.become_exhibitor': 'أصبح عارضاً',
    'participate.exhibitor_desc': 'التعريفات وباقات العارضين',
    'participate.become_partner': 'أصبح راعياً',
    'participate.partner_desc': 'فرص الرعاية',
    'media.menu_title': 'الإعلام',
    # ACCOMMODATION (remaining)
    'accommodation.amenities': 'المرافق',
    'accommodation.book_now': 'احجز الآن',
    'accommodation.breakfast': 'الإفطار',
    'accommodation.check_in': 'تسجيل الوصول',
    'accommodation.check_out': 'المغادرة',
    'accommodation.city': 'المدينة',
    'accommodation.description': 'الوصف',
    'accommodation.distance': 'المسافة',
    'accommodation.email': 'البريد الإلكتروني',
    'accommodation.empty': 'لا توجد فنادق',
    'accommodation.error': 'خطأ',
    'accommodation.featured': 'مميز',
    'accommodation.filter': 'تصفية',
    'accommodation.free_cancellation': 'إلغاء مجاني',
    'accommodation.hotel': 'الفندق',
    'accommodation.image': 'الصورة',
    'accommodation.km': 'كم',
    'accommodation.load_error': 'خطأ في التحميل',
    'accommodation.location': 'الموقع',
    'accommodation.name': 'الاسم',
    'accommodation.no_results': 'لا توجد نتائج',
    'accommodation.partner': 'شريك',
    'accommodation.per_night': 'لكل ليلة',
    'accommodation.phone': 'الهاتف',
    'accommodation.pool': 'المسبح',
    'accommodation.preferred_rate': 'سعر تفضيلي',
    'accommodation.price': 'السعر',
    'accommodation.rate': 'التعريفة',
    'accommodation.rating': 'التقييم',
    'accommodation.restaurant': 'المطعم',
    'accommodation.rooms': 'الغرف',
    'accommodation.search': 'بحث',
    'accommodation.shuttle': 'المكوك',
    'accommodation.stars': 'النجوم',
    'accommodation.subtitle': 'الإقامة بالقرب من المعرض',
    'accommodation.title': 'الإقامة',
    'accommodation.type': 'النوع',
    'accommodation.website': 'الموقع الإلكتروني',
    'accommodation.wifi': 'واي فاي',
    # COUNTDOWN (remaining)
    'countdown.badge': 'العد التنازلي',
    'countdown.button': 'اكتشف',
    'countdown.button_visitor': 'سجّل كزائر',
    'countdown.button_exhibitor': 'أصبح عارضاً',
    'countdown.desc': 'معرض البناء الدولي 2026 في الجديدة',
    'countdown.edition': 'الدورة',
    'countdown.hashtag': '#SIB2026',
    'countdown.label': 'الاحتفاظ بموعد',
    'countdown.location': 'الجديدة - المغرب',
    'countdown.register': 'التسجيل',
    'countdown.save_date': 'احتفظ بالتاريخ',
    'countdown.theme': 'الموضوع',
    'countdown.year': '2026',
    # ADMIN (remaining)
    'admin.analytics_chart': 'رسم بياني للتحليلات',
    'admin.analytics_compare': 'مقارنة',
    'admin.analytics_export': 'تصدير',
    'admin.analytics_filter': 'تصفية',
    'admin.analytics_load_error': 'خطأ في التحميل',
    'admin.analytics_no_data': 'لا توجد بيانات',
    'admin.analytics_overview': 'نظرة عامة',
    'admin.analytics_period': 'الفترة',
    'admin.analytics_subtitle': 'إحصائيات SIB',
    'admin.analytics_title': 'التحليلات',
    'admin.badge_color': 'لون الشارة',
    'admin.badge_config_title': 'إعداد الشارة',
    'admin.badge_font': 'الخط',
    'admin.badge_format': 'الصيغة',
    'admin.badge_layout': 'التخطيط',
    'admin.badge_logo': 'الشعار',
    'admin.badge_preview': 'معاينة الشارة',
    'admin.badge_qr': 'رمز QR',
    'admin.badge_size': 'الحجم',
    'admin.badge_subtitle': 'إعداد قوالب الشارات',
    'admin.badge_template': 'القالب',
    'admin.badge_title': 'الشارة',
    'admin.badge_type': 'نوع الشارة',
    'admin.checkins_count': 'عدد التسجيلات',
    'admin.checkins_export': 'تصدير',
    'admin.checkins_filter': 'تصفية',
    'admin.checkins_load_error': 'خطأ في التحميل',
    'admin.checkins_subtitle': 'تسجيلات الدخول',
    'admin.checkins_title': 'التسجيلات',
    'admin.dashboard_title': 'لوحة التحكم',
    'admin.dashboard_subtitle': 'إدارة SIB 2026',
    'admin.emails_sent': 'بريد مرسل',
    'admin.events_title': 'الأحداث',
    'admin.exhibitors_title': 'العارضون',
    'admin.navbar_dashboard': 'لوحة التحكم',
    'admin.navbar_analytics': 'التحليلات',
    'admin.navbar_users': 'المستخدمون',
    'admin.navbar_exhibitors': 'العارضون',
    'admin.navbar_visitors': 'الزوار',
    'admin.navbar_partners': 'الشركاء',
    'admin.navbar_events': 'الأحداث',
    'admin.navbar_news': 'الأخبار',
    'admin.navbar_media': 'الإعلام',
    'admin.navbar_settings': 'الإعدادات',
    'admin.navbar_logout': 'خروج',
    'admin.partners_title': 'الشركاء',
    'admin.pending_validations': 'التحققات المعلقة',
    'admin.registrations_today': 'التسجيلات اليوم',
    'admin.scan_error': 'خطأ في المسح',
    'admin.scan_success': 'تم المسح بنجاح',
    'admin.scanner_title': 'الماسح',
    'admin.scanners_title': 'الماسحون',
    'admin.settings_title': 'الإعدادات',
    'admin.team_title': 'الفريق',
    'admin.users_title': 'المستخدمون',
    'admin.visitors_title': 'الزوار',
    # EXHIBITOR (remaining)
    'exhibitor.add': 'إضافة عارض',
    'exhibitor.brochure': 'الكتيب',
    'exhibitor.category': 'الفئة',
    'exhibitor.country': 'البلد',
    'exhibitor.create': 'إنشاء عارض',
    'exhibitor.dashboard': 'لوحة التحكم',
    'exhibitor.delete': 'حذف',
    'exhibitor.delete_error': 'خطأ في الحذف',
    'exhibitor.deleted': 'تم الحذف',
    'exhibitor.edit': 'تعديل',
    'exhibitor.employees': 'الموظفون',
    'exhibitor.events': 'الأحداث',
    'exhibitor.industry': 'القطاع',
    'exhibitor.level': 'المستوى',
    'exhibitor.marketing': 'التسويق',
    'exhibitor.media': 'الوسائط',
    'exhibitor.news': 'الأخبار',
    'exhibitor.offers': 'العروض',
    'exhibitor.partners': 'الشركاء',
    'exhibitor.plan': 'الخطة',
    'exhibitor.products_title': 'المنتجات',
    'exhibitor.promo': 'الترويج',
    'exhibitor.registration': 'التسجيل',
    'exhibitor.save': 'حفظ',
    'exhibitor.save_error': 'خطأ في الحفظ',
    'exhibitor.saved': 'تم الحفظ',
    'exhibitor.services': 'الخدمات',
    'exhibitor.size': 'الحجم',
    'exhibitor.status': 'الحالة',
    'exhibitor.subscription': 'الاشتراك',
    'exhibitor.type': 'النوع',
    'exhibitor.update': 'تحديث',
    'exhibitor.update_error': 'خطأ في التحديث',
    'exhibitor.updated': 'تم التحديث',
    'exhibitor.verified': 'معتمد',
    'exhibitor.visitors': 'الزوار',
    'exhibitor.year': 'السنة',
    # PARTNER (remaining)
    'partner.accept': 'قبول',
    'partner.address': 'العنوان',
    'partner.approve': 'موافقة',
    'partner.approved': 'معتمد',
    'partner.brochure': 'الكتيب',
    'partner.category': 'الفئة',
    'partner.city': 'المدينة',
    'partner.collaborators': 'المتعاونون',
    'partner.contact_desc': 'التواصل مع الشريك',
    'partner.country': 'البلد',
    'partner.exhibitors': 'العارضون',
    'partner.info': 'المعلومات',
    'partner.logo_url': 'رابط الشعار',
    'partner.media': 'الوسائط',
    'partner.media_title': 'الوسيلة الإعلامية',
    'partner.news': 'الأخبار',
    'partner.notes': 'الملاحظات',
    'partner.pending': 'قيد الانتظار',
    'partner.phone2': 'الهاتف الثاني',
    'partner.products': 'المنتجات',
    'partner.reject': 'رفض',
    'partner.rejected': 'مرفوض',
    'partner.services': 'الخدمات',
    'partner.social_links': 'الروابط الاجتماعية',
    'partner.tier': 'الدرجة',
    'partner.verified': 'معتمد',
    'partner.visitors': 'الزوار',
    # PAYMENT (remaining)
    'payment.bank_transfer': 'تحويل بنكي',
    'payment.bank_info': 'معلومات بنكية',
    'payment.card_payment': 'دفع بالبطاقة',
    'payment.cash': 'نقداً',
    'payment.checkout': 'إتمام الطلب',
    'payment.complete': 'مكتمل',
    'payment.download_invoice': 'تنزيل الفاتورة',
    'payment.iban': 'IBAN',
    'payment.installment': 'تقسيط',
    'payment.online': 'عبر الإنترنت',
    'payment.paypal': 'PayPal',
    'payment.plan': 'الخطة',
    'payment.quantity': 'الكمية',
    'payment.save_card': 'حفظ البطاقة',
    'payment.stripe': 'Stripe',
    'payment.swift': 'SWIFT',
    'payment.unit_price': 'سعر الوحدة',
    # COMMON (remaining)
    'common.address_line2': 'عنوان إضافي',
    'common.bio': 'نبذة',
    'common.birth_date': 'تاريخ الميلاد',
    'common.category': 'الفئة',
    'common.clear': 'مسح',
    'common.company_size': 'حجم الشركة',
    'common.confirm_delete': 'هل أنت متأكد من الحذف؟',
    'common.created_at': 'تاريخ الإنشاء',
    'common.currency': 'العملة',
    'common.date_from': 'من تاريخ',
    'common.date_to': 'إلى تاريخ',
    'common.day': 'يوم',
    'common.days': 'أيام',
    'common.delete_success': 'تم الحذف بنجاح',
    'common.duration': 'المدة',
    'common.fax': 'الفاكس',
    'common.field_required': 'الحقل مطلوب',
    'common.file': 'الملف',
    'common.files': 'الملفات',
    'common.first': 'الأول',
    'common.folder': 'المجلد',
    'common.format': 'الصيغة',
    'common.free': 'مجاني',
    'common.gender': 'الجنس',
    'common.go_back': 'رجوع',
    'common.go_home': 'الرئيسية',
    'common.header': 'الترويسة',
    'common.hour': 'ساعة',
    'common.hours': 'ساعات',
    'common.id': 'المعرّف',
    'common.industry': 'القطاع',
    'common.item': 'عنصر',
    'common.items': 'عناصر',
    'common.key': 'المفتاح',
    'common.last': 'الأخير',
    'common.last_update': 'آخر تحديث',
    'common.level': 'المستوى',
    'common.list': 'القائمة',
    'common.location': 'الموقع',
    'common.logo': 'الشعار',
    'common.map': 'الخريطة',
    'common.menu': 'القائمة',
    'common.min': 'الدقيقة',
    'common.minutes': 'دقائق',
    'common.mobile': 'الجوّال',
    'common.mode': 'الوضع',
    'common.month': 'شهر',
    'common.months': 'أشهر',
    'common.more': 'المزيد',
    'common.no_image': 'لا توجد صورة',
    'common.note': 'ملاحظة',
    'common.number': 'الرقم',
    'common.order': 'الترتيب',
    'common.other': 'أخرى',
    'common.pending': 'قيد الانتظار',
    'common.phone2': 'هاتف ثانٍ',
    'common.photo': 'الصورة',
    'common.position_num': 'الموضع',
    'common.postal_code': 'الرمز البريدي',
    'common.premium': 'مميز',
    'common.priority': 'الأولوية',
    'common.profile_image': 'صورة الملف',
    'common.province': 'المقاطعة',
    'common.qty': 'الكمية',
    'common.quantity': 'الكمية',
    'common.rating': 'التقييم',
    'common.region': 'المنطقة',
    'common.role': 'الدور',
    'common.save_success': 'تم الحفظ بنجاح',
    'common.send': 'إرسال',
    'common.size': 'الحجم',
    'common.sort': 'ترتيب',
    'common.start_date': 'تاريخ البداية',
    'common.state': 'الولاية',
    'common.street': 'الشارع',
    'common.summary': 'الملخص',
    'common.tag': 'الوسم',
    'common.tags': 'الوسوم',
    'common.text': 'النص',
    'common.tier': 'الدرجة',
    'common.timezone': 'المنطقة الزمنية',
    'common.today': 'اليوم',
    'common.token': 'الرمز',
    'common.topic': 'الموضوع',
    'common.topics': 'المواضيع',
    'common.type2': 'النوع',
    'common.uid': 'المعرّف',
    'common.updated_at': 'تاريخ التحديث',
    'common.url': 'الرابط',
    'common.user': 'المستخدم',
    'common.username': 'اسم المستخدم',
    'common.value': 'القيمة',
    'common.verified': 'معتمد',
    'common.visibility': 'الظهور',
    'common.week': 'أسبوع',
    'common.weeks': 'أسابيع',
    'common.year': 'سنة',
    'common.years': 'سنوات',
    'common.zip': 'الرمز البريدي',
    # NETWORKING (remaining)
    'networking.accepted': 'مقبول',
    'networking.availability': 'الإتاحة',
    'networking.block': 'حجب',
    'networking.blocked': 'محجوب',
    'networking.calendar': 'التقويم',
    'networking.cancel': 'إلغاء',
    'networking.chat': 'محادثة',
    'networking.city': 'المدينة',
    'networking.confirm_meeting': 'تأكيد الاجتماع',
    'networking.country': 'البلد',
    'networking.decline': 'رفض',
    'networking.declined': 'مرفوض',
    'networking.duration': 'المدة',
    'networking.edit_profile': 'تعديل الملف',
    'networking.exhibitor': 'العارض',
    'networking.export': 'تصدير',
    'networking.follow': 'متابعة',
    'networking.following': 'يتابع',
    'networking.industry': 'القطاع',
    'networking.invite': 'دعوة',
    'networking.language': 'اللغة',
    'networking.location': 'الموقع',
    'networking.meeting_date': 'تاريخ الاجتماع',
    'networking.meeting_location': 'مكان الاجتماع',
    'networking.meeting_time': 'وقت الاجتماع',
    'networking.meeting_topic': 'موضوع الاجتماع',
    'networking.my_meetings': 'اجتماعاتي',
    'networking.my_profile': 'ملفي الشخصي',
    'networking.note': 'ملاحظة',
    'networking.online': 'عبر الإنترنت',
    'networking.partner': 'الشريك',
    'networking.pending': 'قيد الانتظار',
    'networking.photo': 'الصورة',
    'networking.reschedule': 'إعادة الجدولة',
    'networking.save': 'حفظ',
    'networking.social': 'الشبكات الاجتماعية',
    'networking.topics': 'المواضيع',
    'networking.type': 'النوع',
    'networking.unfollow': 'إلغاء المتابعة',
    'networking.visitor': 'الزائر',
    'networking.website': 'الموقع الإلكتروني',
    # BADGE (remaining)
    'badge.activate': 'تفعيل',
    'badge.active': 'نشط',
    'badge.company': 'الشركة',
    'badge.country': 'البلد',
    'badge.create': 'إنشاء شارة',
    'badge.created': 'تم إنشاء الشارة',
    'badge.create_error': 'خطأ في الإنشاء',
    'badge.deactivate': 'تعطيل',
    'badge.delete': 'حذف',
    'badge.delete_error': 'خطأ في الحذف',
    'badge.deleted': 'تم الحذف',
    'badge.email': 'البريد الإلكتروني',
    'badge.expire': 'انتهاء الصلاحية',
    'badge.expired': 'منتهي الصلاحية',
    'badge.id': 'رقم الشارة',
    'badge.load_error': 'خطأ في التحميل',
    'badge.name': 'الاسم',
    'badge.number': 'رقم الشارة',
    'badge.pending': 'قيد الانتظار',
    'badge.phone': 'الهاتف',
    'badge.photo': 'الصورة',
    'badge.position': 'المنصب',
    'badge.regenerate': 'إعادة الإنشاء',
    'badge.register': 'التسجيل للحصول على شارة',
    'badge.registered': 'مسجل',
    'badge.revoke': 'إلغاء',
    'badge.revoked': 'ملغى',
    'badge.sector': 'القطاع',
    'badge.status': 'الحالة',
    'badge.type': 'النوع',
    'badge.verify': 'التحقق',
    'badge.verified': 'معتمد',
    # MINISITE (remaining)
    'minisite.address': 'العنوان',
    'minisite.cancel': 'إلغاء',
    'minisite.categories': 'الفئات',
    'minisite.category': 'الفئة',
    'minisite.certifications': 'الشهادات',
    'minisite.city': 'المدينة',
    'minisite.company_size': 'حجم الشركة',
    'minisite.country': 'البلد',
    'minisite.cover': 'الغلاف',
    'minisite.create': 'إنشاء',
    'minisite.created': 'تم الإنشاء',
    'minisite.delete': 'حذف',
    'minisite.delete_error': 'خطأ في الحذف',
    'minisite.deleted': 'تم الحذف',
    'minisite.founded': 'تأسست سنة',
    'minisite.gallery_empty': 'المعرض فارغ',
    'minisite.industry': 'القطاع',
    'minisite.languages': 'اللغات',
    'minisite.location': 'الموقع',
    'minisite.products_empty': 'لا توجد منتجات',
    'minisite.province': 'المقاطعة',
    'minisite.services': 'الخدمات',
    'minisite.services_empty': 'لا توجد خدمات',
    'minisite.size': 'الحجم',
    'minisite.status': 'الحالة',
    'minisite.street': 'الشارع',
    'minisite.tagline': 'الشعار',
    'minisite.type': 'النوع',
    'minisite.update': 'تحديث',
    'minisite.update_error': 'خطأ في التحديث',
    'minisite.updated': 'تم التحديث',
    'minisite.video': 'الفيديو',
    'minisite.zip': 'الرمز البريدي',
    # DASHBOARD (remaining)
    'dashboard.admin': 'الإدارة',
    'dashboard.analytics_title': 'التحليلات',
    'dashboard.appointments_today': 'مواعيد اليوم',
    'dashboard.completed': 'المكتملون',
    'dashboard.confirmed': 'المؤكدون',
    'dashboard.exhibitor': 'العارض',
    'dashboard.my_events': 'أحداثي',
    'dashboard.my_favorites': 'مفضلتي',
    'dashboard.my_meetings': 'اجتماعاتي',
    'dashboard.my_messages': 'رسائلي',
    'dashboard.my_profile': 'ملفي',
    'dashboard.my_scans': 'مسوحاتي',
    'dashboard.my_settings': 'إعداداتي',
    'dashboard.overview': 'نظرة عامة',
    'dashboard.partner': 'الشريك',
    'dashboard.recent_registrations': 'التسجيلات الأخيرة',
    'dashboard.recent_scans': 'المسوحات الأخيرة',
    'dashboard.revenue_today': 'إيرادات اليوم',
    'dashboard.role': 'الدور',
    'dashboard.scans_today': 'مسوحات اليوم',
    'dashboard.total_revenue': 'إجمالي الإيرادات',
    'dashboard.user': 'المستخدم',
    'dashboard.visitor': 'الزائر',
    # HOME (remaining)
    'home.about': 'حول SIB',
    'home.about_subtitle': 'اكتشف المعرض الدولي للبناء',
    'home.all_news': 'جميع الأخبار',
    'home.categories': 'الفئات',
    'home.contact': 'اتصل بنا',
    'home.dates': 'التواريخ',
    'home.exhibitors': 'العارضون',
    'home.exhibitions': 'المعارض',
    'home.explore': 'استكشف',
    'home.featured': 'مميز',
    'home.location': 'الجديدة - المغرب',
    'home.news': 'الأخبار',
    'home.pavilions': 'الأجنحة',
    'home.plan_visit': 'خطط لزيارتك',
    'home.register_now': 'سجّل الآن',
    'home.sectors': 'القطاعات',
    'home.testimonials': 'الشهادات',
    'home.videos': 'الفيديوهات',
    # ANALYTICS (remaining)
    'analytics.active_users': 'المستخدمون النشطون',
    'analytics.avg_session': 'متوسط الجلسة',
    'analytics.badge_scans': 'مسوحات الشارات',
    'analytics.bounce_rate': 'معدل الارتداد',
    'analytics.countries': 'الدول',
    'analytics.exhibitors': 'العارضون',
    'analytics.export_excel': 'تصدير Excel',
    'analytics.export_pdf': 'تصدير PDF',
    'analytics.filter': 'تصفية',
    'analytics.geo': 'الجغرافيا',
    'analytics.kpi': 'مؤشرات الأداء',
    'analytics.meetings': 'الاجتماعات',
    'analytics.messages': 'الرسائل',
    'analytics.new_users': 'مستخدمون جدد',
    'analytics.partners': 'الشركاء',
    'analytics.registration': 'التسجيل',
    'analytics.retention': 'الاحتفاظ',
    'analytics.sector': 'القطاع',
    'analytics.sessions_count': 'عدد الجلسات',
    'analytics.share': 'مشاركة',
    'analytics.sources': 'المصادر',
    'analytics.type': 'النوع',
    'analytics.unique_visitors': 'الزوار الفريدون',
    'analytics.users': 'المستخدمون',
    'analytics.views': 'المشاهدات',
    # REGISTER (remaining)
    'register.city': 'المدينة',
    'register.country_code': 'رمز البلد',
    'register.dob': 'تاريخ الميلاد',
    'register.gender': 'الجنس',
    'register.gender_female': 'أنثى',
    'register.gender_male': 'ذكر',
    'register.industry': 'القطاع',
    'register.language': 'اللغة',
    'register.level': 'المستوى',
    'register.linkedin': 'LinkedIn',
    'register.nationality': 'الجنسية',
    'register.password_weak': 'كلمة المرور ضعيفة',
    'register.password_medium': 'كلمة المرور متوسطة',
    'register.password_strong': 'كلمة المرور قوية',
    'register.referral': 'الإحالة',
    'register.state': 'الولاية',
    'register.street': 'الشارع',
    'register.terms_required': 'يجب قبول الشروط',
    'register.twitter': 'Twitter',
    'register.website': 'الموقع الإلكتروني',
    'register.zip': 'الرمز البريدي',
    # LOGIN (remaining)
    'login.back': 'رجوع',
    'login.close': 'إغلاق',
    'login.confirm_password': 'تأكيد كلمة المرور',
    'login.contact_support': 'اتصل بالدعم',
    'login.create_account': 'إنشاء حساب',
    'login.email_required': 'البريد الإلكتروني مطلوب',
    'login.email_sent': 'تم إرسال البريد الإلكتروني',
    'login.invalid_email': 'البريد الإلكتروني غير صالح',
    'login.loading': 'جارٍ التحميل...',
    'login.logout': 'تسجيل الخروج',
    'login.new_password': 'كلمة مرور جديدة',
    'login.or_continue': 'أو المتابعة بـ',
    'login.password_required': 'كلمة المرور مطلوبة',
    'login.reset_password': 'إعادة تعيين كلمة المرور',
    'login.reset_sent': 'تم إرسال رابط الإعادة',
    'login.sign_up': 'إنشاء حساب',
    'login.update_password': 'تحديث كلمة المرور',
    # CHATBOT (remaining)
    'chatbot.attachment': 'مرفق',
    'chatbot.audio': 'صوتي',
    'chatbot.clear': 'مسح',
    'chatbot.date': 'التاريخ',
    'chatbot.description': 'الوصف',
    'chatbot.details': 'التفاصيل',
    'chatbot.emoji': 'إيموجي',
    'chatbot.export': 'تصدير',
    'chatbot.filter': 'تصفية',
    'chatbot.image': 'صورة',
    'chatbot.info': 'معلومات',
    'chatbot.link': 'رابط',
    'chatbot.list': 'قائمة',
    'chatbot.load_more': 'تحميل المزيد',
    'chatbot.microphone': 'ميكروفون',
    'chatbot.more': 'المزيد',
    'chatbot.no_history': 'لا يوجد سجل',
    'chatbot.preview': 'معاينة',
    'chatbot.quick_reply': 'رد سريع',
    'chatbot.read': 'مقروء',
    'chatbot.received': 'تم الاستقبال',
    'chatbot.search': 'بحث',
    'chatbot.sent': 'تم الإرسال',
    'chatbot.settings': 'الإعدادات',
    'chatbot.status': 'الحالة',
    'chatbot.timestamp': 'الوقت',
    'chatbot.video': 'فيديو',
    # CONTACT (remaining)
    'contact.company': 'الشركة',
    'contact.country': 'البلد',
    'contact.department': 'القسم',
    'contact.directions': 'الاتجاهات',
    'contact.form': 'نموذج الاتصال',
    'contact.headquarters': 'المقر الرئيسي',
    'contact.info': 'معلومات الاتصال',
    'contact.map_link': 'عرض في الخريطة',
    'contact.office': 'المكتب',
    'contact.organization': 'المنظمة',
    'contact.person': 'الشخص',
    'contact.position': 'المنصب',
    'contact.privacy': 'خصوصية',
    'contact.region': 'المنطقة',
    'contact.success': 'تم الإرسال بنجاح',
    'contact.type': 'النوع',
    'contact.website': 'الموقع الإلكتروني',
    # MEDIA (remaining)
    'media.add': 'إضافة وسيط',
    'media.all': 'الكل',
    'media.author': 'الكاتب',
    'media.category': 'الفئة',
    'media.create': 'إنشاء',
    'media.date': 'التاريخ',
    'media.delete': 'حذف',
    'media.delete_error': 'خطأ في الحذف',
    'media.deleted': 'تم الحذف',
    'media.description': 'الوصف',
    'media.duration': 'المدة',
    'media.edit': 'تعديل',
    'media.embed': 'تضمين',
    'media.empty': 'لا يوجد محتوى',
    'media.error': 'خطأ',
    'media.featured': 'مميز',
    'media.filter': 'تصفية',
    'media.image': 'الصورة',
    'media.keywords': 'الكلمات المفتاحية',
    'media.language': 'اللغة',
    'media.link': 'الرابط',
    'media.list': 'قائمة الوسائط',
    'media.no_results': 'لا توجد نتائج',
    'media.platform': 'المنصة',
    'media.play': 'تشغيل',
    'media.publish': 'نشر',
    'media.published': 'منشور',
    'media.save': 'حفظ',
    'media.save_error': 'خطأ في الحفظ',
    'media.saved': 'تم الحفظ',
    'media.search': 'بحث في الوسائط',
    'media.share': 'مشاركة',
    'media.speakers': 'المتحدثون',
    'media.status': 'الحالة',
    'media.subtitle': 'محتوى SIB',
    'media.tags': 'الوسوم',
    'media.thumbnail': 'الصورة المصغرة',
    'media.title': 'الوسائط',
    'media.type': 'النوع',
    'media.unpublish': 'إلغاء النشر',
    'media.unpublished': 'غير منشور',
    'media.update': 'تحديث',
    'media.update_error': 'خطأ في التحديث',
    'media.updated': 'تم التحديث',
    'media.url': 'الرابط',
    'media.video': 'الفيديو',
    'media.views': 'المشاهدات',
    'media.youtube': 'YouTube',
    # PARTNERS
    'partners.add': 'إضافة شريك',
    'partners.all': 'جميع الشركاء',
    'partners.category': 'الفئة',
    'partners.contact': 'اتصل',
    'partners.description': 'الوصف',
    'partners.details': 'التفاصيل',
    'partners.email': 'البريد الإلكتروني',
    'partners.empty': 'لا يوجد شركاء',
    'partners.filter': 'تصفية',
    'partners.level': 'المستوى',
    'partners.load_error': 'خطأ في التحميل',
    'partners.logo': 'الشعار',
    'partners.name': 'الاسم',
    'partners.phone': 'الهاتف',
    'partners.search': 'بحث في الشركاء',
    'partners.sector': 'القطاع',
    'partners.subtitle': 'شركاء SIB',
    'partners.title': 'الشركاء',
    'partners.type': 'النوع',
    'partners.view': 'عرض',
    'partners.website': 'الموقع الإلكتروني',
    # SCANS (remaining)
    'scans.all': 'الكل',
    'scans.booth': 'الجناح',
    'scans.confirmed': 'مؤكد',
    'scans.created_at': 'تاريخ الإنشاء',
    'scans.device': 'الجهاز',
    'scans.event': 'الحدث',
    'scans.gate': 'البوابة',
    'scans.invalid': 'غير صالح',
    'scans.operator': 'المشغّل',
    'scans.pending': 'قيد الانتظار',
    'scans.reason': 'السبب',
    'scans.rejected': 'مرفوض',
    'scans.scan_id': 'رقم المسح',
    'scans.sector': 'القطاع',
    'scans.valid': 'صالح',
    'scans.visitor': 'الزائر',
    # SESSION_REG (remaining)
    'session_reg.location': 'الموقع',
    'session_reg.notes': 'الملاحظات',
    'session_reg.organizer': 'المنظم',
    'session_reg.room': 'القاعة',
}

# ─────────────────────────────────────────────────────────────────────────────
content = open('src/store/translations.ts', encoding='utf-8').read()

import re

ar_start = re.search(r'\n  ar:\s*\{', content)
ar_end_match = re.search(r'\n  es:\s*\{', content)

ar_block_start = ar_start.end()
ar_block_end = ar_end_match.start()
ar_block = content[ar_block_start:ar_block_end]

fixed = 0

for key, ar_value in AR2.items():
    pattern = r"('" + re.escape(key) + r"'\s*:\s*')([^']*?)(')"
    replacement = r'\g<1>' + ar_value.replace('\\', '\\\\') + r'\3'
    new_ar_block, count = re.subn(pattern, replacement, ar_block)
    if count > 0:
        ar_block = new_ar_block
        fixed += count

content = content[:ar_block_start] + ar_block + content[ar_block_end:]
open('src/store/translations.ts', 'w', encoding='utf-8').write(content)
print(f"Clés corrigées: {fixed}")

# Vérification
content2 = open('src/store/translations.ts', encoding='utf-8').read()
ar_m = re.search(r'\n  ar:\s*\{(.+?)\n  \},?\s*\n\s*es:', content2, re.DOTALL)
if ar_m:
    ar_b = ar_m.group(1)
    keys2 = re.findall(r"'([^']+)'\s*:\s*'([^']*)'", ar_b)
    total2 = len(keys2)
    good2 = sum(1 for k, v in keys2 if any('\u0600' <= c <= '\u06ff' for c in v))
    print(f"Résultat: {good2}/{total2} clés AR avec texte arabe ({100*good2//total2}%)")
