"""
Script de traduction arabe complète.
Lit ar_keys_to_fix.txt (clé|valeur_actuelle_FR/EN)
et remplace chaque valeur par la traduction arabe correcte dans translations.ts.
"""
import re

# ─────────────────────────────────────────────────────────────────────────────
# Dictionnaire complet clé → traduction arabe
# ─────────────────────────────────────────────────────────────────────────────
AR = {
    # NAV
    'nav.chat': 'المحادثة',
    'nav.le_salon': 'المعرض',
    'nav.exposer': 'العرض',
    'nav.visiter': 'الزيارة',
    'nav.programme': 'البرنامج',
    'nav.partenaires': 'الشركاء',
    'nav.media': 'الإعلام',
    'nav.contact': 'اتصل بنا',
    'nav.reseautage': 'التواصل',
    'nav.sponsors': 'الرعاة',
    'nav.networking': 'التواصل',
    # SALON
    'salon.presentation': 'عرض تقديمي وأرقام رئيسية',
    'salon.presentation_desc': 'اكتشف SIB وأرقامه ومنظميه',
    'salon.nouveautes': 'مستجدات SIB',
    'salon.nouveautes_desc': 'ابتكارات هذه الدورة',
    'salon.secteurs': 'قطاعات النشاط',
    'salon.secteurs_desc': 'قطاعات صناعة البناء الـ 12 الممثلة',
    'salon.editions': 'الدورات منذ 1986',
    'salon.editions_desc': 'تاريخ 20 دورة من SIB',
    'salon.telechargements': 'التنزيلات',
    'salon.telechargements_desc': 'الكتيبات والكتالوجات والوثائق PDF',
    'salon.actualites': 'الأخبار',
    'salon.actualites_desc': 'آخر أخبار المعرض',
    'salon.pavilions': 'الأجنحة',
    'salon.pavilions_desc': 'استكشف أجنحة المعرض',
    'salon.plan': 'خريطة القاعة',
    'salon.plan_desc': 'تصفح خريطة المعرض',
    # EXPOSER
    'exposer.pourquoi': 'لماذا تعرض؟',
    'exposer.pourquoi_desc': 'مزايا أن تكون عارضاً',
    'exposer.espaces': 'فضاءات SIB',
    'exposer.espaces_desc': 'الفضاءات الموضوعية الـ 5 للمعرض',
    'exposer.forfaits': 'باقات العارضين',
    'exposer.forfaits_desc': 'التعريفات وباقات الأجنحة',
    'exposer.annuaire': 'دليل العارضين',
    'exposer.annuaire_desc': 'جميع عارضي SIB 2026',
    'exposer.reserver': 'حجز جناح',
    'exposer.reserver_desc': 'التعريفات والباقات والحجز',
    'exposer.location': 'تأجير المعدات',
    'exposer.location_desc': 'كتالوج المعدات للإيجار',
    # VISITER
    'visiter.pourquoi': 'لماذا تزور؟',
    'visiter.pourquoi_desc': 'أسباب الحضور إلى SIB',
    'visiter.infos': 'معلومات عملية',
    'visiter.infos_desc': 'المكان والتوقيت والوصول والمواصلات',
    'visiter.badge': 'الحصول على شارة',
    'visiter.badge_desc': 'التسجيل للحصول على شارة الزيارة',
    'visiter.vip': 'التسجيل VIP',
    'visiter.vip_desc': 'وصول حصري وخدمات متميزة',
    'visiter.hebergement': 'الإقامة',
    'visiter.hebergement_desc': 'الفنادق الموصى بها بالقرب من SIB',
    'visiter.speakers': 'المتحدثون',
    'visiter.speakers_desc': 'المتحدثون والخبراء في SIB 2026',
    'visiter.plan': 'خريطة القاعة',
    'visiter.plan_desc': 'التنقل في المعرض',
    # PARTENAIRES
    'partenaires.devenir': 'أصبح شريكاً',
    'partenaires.devenir_desc': 'اكتشف فرص الشراكة',
    'partenaires.annuaire': 'دليل الشركاء',
    'partenaires.annuaire_desc': 'جميع شركاء SIB',
    'partenaires.media_partner': 'شريك إعلامي',
    'partenaires.media_partner_desc': 'التسجيل كشريك إعلامي',
    # MEDIA
    'media.webinars': 'ندوات الويب',
    'media.webinars_desc': 'ندوات الويب الحية والمسجلة',
    'media.podcasts': 'البودكاست',
    'media.podcasts_desc': 'جميع حلقات البودكاست',
    'media.capsules': 'كبسولات فيديو',
    'media.capsules_desc': 'مقاطع فيديو قصيرة',
    'media.live_studio': 'الاستوديو المباشر',
    'media.live_studio_desc': 'البث المباشر من SIB',
    'media.best_moments': 'أبرز اللحظات',
    'media.best_moments_desc': 'اللحظات المميزة',
    'media.testimonials': 'الشهادات',
    'media.testimonials_desc': 'شهادات العارضين والزوار',
    'media.library': 'المكتبة الإعلامية',
    'media.library_desc': 'جميع المحتويات الإعلامية',
    # COMMON
    'common.save': 'حفظ',
    'common.cancel': 'إلغاء',
    'common.edit': 'تعديل',
    'common.delete': 'حذف',
    'common.add': 'إضافة',
    'common.create': 'إنشاء',
    'common.update': 'تحديث',
    'common.close': 'إغلاق',
    'common.back': 'رجوع',
    'common.next': 'التالي',
    'common.previous': 'السابق',
    'common.submit': 'إرسال',
    'common.confirm': 'تأكيد',
    'common.loading': 'جارٍ التحميل...',
    'common.saving': 'جارٍ الحفظ...',
    'common.search': 'بحث',
    'common.filter': 'تصفية',
    'common.view': 'عرض',
    'common.download': 'تنزيل',
    'common.upload': 'رفع',
    'common.copy': 'نسخ',
    'common.copied': 'تم النسخ',
    'common.yes': 'نعم',
    'common.no': 'لا',
    'common.ok': 'موافق',
    'common.error': 'خطأ',
    'common.success': 'نجاح',
    'common.warning': 'تحذير',
    'common.required': 'مطلوب',
    'common.optional': 'اختياري',
    'common.all': 'الكل',
    'common.none': 'لا شيء',
    'common.unknown': 'غير معروف',
    'common.name': 'الاسم',
    'common.email': 'البريد الإلكتروني',
    'common.phone': 'الهاتف',
    'common.address': 'العنوان',
    'common.city': 'المدينة',
    'common.country': 'البلد',
    'common.date': 'التاريخ',
    'common.time': 'الوقت',
    'common.description': 'الوصف',
    'common.status': 'الحالة',
    'common.type': 'النوع',
    'common.active': 'نشط',
    'common.inactive': 'غير نشط',
    'common.enabled': 'مفعّل',
    'common.disabled': 'معطّل',
    'common.default': 'افتراضي',
    'common.public': 'عام',
    'common.private': 'خاص',
    'common.new': 'جديد',
    'common.title': 'العنوان',
    'common.subtitle': 'العنوان الفرعي',
    'common.content': 'المحتوى',
    'common.image': 'الصورة',
    'common.link': 'الرابط',
    'common.save_error': 'خطأ في الحفظ',
    'common.load_error': 'خطأ في التحميل',
    'common.delete_confirm': 'هل أنت متأكد من الحذف؟',
    'common.delete_error': 'خطأ في الحذف',
    'common.update_error': 'خطأ في التحديث',
    'common.create_error': 'خطأ في الإنشاء',
    'common.send_error': 'خطأ في الإرسال',
    'common.not_found': 'غير موجود',
    'common.empty': 'فارغ',
    'common.no_results': 'لا توجد نتائج',
    'common.select': 'اختيار',
    'common.select_all': 'تحديد الكل',
    'common.deselect_all': 'إلغاء تحديد الكل',
    'common.actions': 'الإجراءات',
    'common.details': 'التفاصيل',
    'common.preview': 'معاينة',
    'common.settings': 'الإعدادات',
    'common.profile': 'الملف الشخصي',
    'common.logout': 'تسجيل الخروج',
    'common.login': 'تسجيل الدخول',
    'common.register': 'إنشاء حساب',
    'common.password': 'كلمة المرور',
    'common.confirm_password': 'تأكيد كلمة المرور',
    'common.firstname': 'الاسم الأول',
    'common.lastname': 'اسم العائلة',
    'common.company': 'الشركة',
    'common.position': 'المنصب',
    'common.website': 'الموقع الإلكتروني',
    'common.total': 'المجموع',
    'common.count': 'العدد',
    'common.page': 'الصفحة',
    'common.of': 'من',
    'common.per_page': 'لكل صفحة',
    'common.show': 'إظهار',
    'common.hide': 'إخفاء',
    'common.expand': 'توسيع',
    'common.collapse': 'طي',
    'common.refresh': 'تحديث',
    'common.export': 'تصدير',
    'common.import': 'استيراد',
    'common.print': 'طباعة',
    'common.share': 'مشاركة',
    'common.help': 'مساعدة',
    'common.about': 'حول',
    'common.version': 'الإصدار',
    'common.language': 'اللغة',
    'common.theme': 'المظهر',
    'common.notifications': 'الإشعارات',
    'common.messages': 'الرسائل',
    'common.appointments': 'المواعيد',
    'common.dashboard': 'لوحة التحكم',
    # ACTIONS
    'actions.add': 'إضافة',
    'actions.cancel': 'إلغاء',
    'actions.copy': 'نسخ',
    'actions.loading': 'جارٍ التحميل...',
    'actions.schedule_meeting': 'جدولة اجتماع',
    'actions.view_details': 'عرض التفاصيل',
    'actions.edit': 'تعديل',
    'actions.delete': 'حذف',
    'actions.save': 'حفظ',
    'actions.update': 'تحديث',
    'actions.create': 'إنشاء',
    'actions.send': 'إرسال',
    'actions.approve': 'موافقة',
    'actions.reject': 'رفض',
    'actions.activate': 'تفعيل',
    'actions.deactivate': 'تعطيل',
    'actions.confirm': 'تأكيد',
    'actions.back': 'رجوع',
    'actions.close': 'إغلاق',
    'actions.submit': 'إرسال',
    'actions.export': 'تصدير',
    'actions.import': 'استيراد',
    'actions.download': 'تنزيل',
    'actions.upload': 'رفع',
    'actions.refresh': 'تحديث',
    'actions.search': 'بحث',
    'actions.filter': 'تصفية',
    'actions.reset': 'إعادة تعيين',
    'actions.publish': 'نشر',
    'actions.unpublish': 'إلغاء النشر',
    'actions.preview': 'معاينة',
    'actions.generate': 'توليد',
    'actions.resend': 'إعادة الإرسال',
    # LOGIN / AUTH
    'login.title': 'تسجيل الدخول',
    'login.subtitle': 'أدخل بيانات اعتمادك للمتابعة',
    'login.email': 'البريد الإلكتروني',
    'login.email_placeholder': 'أدخل بريدك الإلكتروني',
    'login.password': 'كلمة المرور',
    'login.password_placeholder': 'أدخل كلمة المرور',
    'login.magic_link': 'رابط سحري',
    'login.magic_link_desc': 'استلم رابطاً للدخول بدون كلمة مرور',
    'login.send_magic_link': 'إرسال الرابط السحري',
    'login.magic_link_sent': 'تم إرسال الرابط! تحقق من بريدك.',
    'login.submit': 'تسجيل الدخول',
    'login.forgot_password': 'نسيت كلمة المرور؟',
    'login.no_account': 'ليس لديك حساب؟',
    'login.register_link': 'إنشاء حساب',
    'login.or': 'أو',
    'login.error': 'خطأ في تسجيل الدخول',
    'login.invalid_credentials': 'بيانات الاعتماد غير صحيحة',
    'login.welcome': 'مرحباً بك',
    'login.welcome_back': 'مرحباً بعودتك',
    # REGISTER
    'register.title': 'إنشاء حساب',
    'register.subtitle': 'أنشئ حسابك للوصول إلى SIB 2026',
    'register.firstname': 'الاسم الأول',
    'register.lastname': 'اسم العائلة',
    'register.email': 'البريد الإلكتروني',
    'register.phone': 'الهاتف',
    'register.company': 'الشركة',
    'register.position': 'المنصب',
    'register.country': 'البلد',
    'register.password': 'كلمة المرور',
    'register.confirm_password': 'تأكيد كلمة المرور',
    'register.submit': 'إنشاء الحساب',
    'register.already_account': 'لديك حساب بالفعل؟',
    'register.login_link': 'تسجيل الدخول',
    'register.success': 'تم إنشاء الحساب بنجاح!',
    'register.error': 'خطأ في إنشاء الحساب',
    'register.exhibitor_title': 'التسجيل كعارض',
    'register.visitor_title': 'التسجيل كزائر',
    'register.partner_title': 'التسجيل كشريك',
    'register.type_visitor': 'زائر',
    'register.type_exhibitor': 'عارض',
    'register.type_partner': 'شريك',
    'register.select_type': 'اختر نوع التسجيل',
    'register.select_type_desc': 'حدد كيف ستشارك في SIB 2026',
    'register.personal_info': 'المعلومات الشخصية',
    'register.company_info': 'معلومات الشركة',
    'register.confirm_step': 'التأكيد',
    'register.step': 'الخطوة',
    'register.of': 'من',
    'register.required_fields': 'الحقول المطلوبة',
    'register.terms': 'شروط الاستخدام',
    'register.accept_terms': 'أوافق على شروط الاستخدام',
    'register.privacy': 'سياسة الخصوصية',
    'register.name_required': 'الاسم مطلوب',
    'register.email_required': 'البريد الإلكتروني مطلوب',
    'register.email_invalid': 'البريد الإلكتروني غير صالح',
    'register.password_required': 'كلمة المرور مطلوبة',
    'register.password_min': 'كلمة المرور قصيرة جداً (8 أحرف على الأقل)',
    'register.passwords_match': 'كلمتا المرور غير متطابقتين',
    'register.visitor_subtitle': 'احصل على شارتك للدخول إلى SIB 2026',
    'register.exhibitor_subtitle': 'احجز جناحك في SIB 2026',
    'register.partner_subtitle': 'اشترك كشريك في SIB 2026',
    'register.free_badge': 'شارة مجانية',
    'register.vip_badge': 'شارة VIP',
    'register.pro_badge': 'شارة Pro',
    'register.sector': 'القطاع',
    'register.sectors': 'القطاعات',
    'register.booth_size': 'حجم الجناح',
    'register.message': 'رسالة',
    'register.how_heard': 'كيف سمعت عنا؟',
    'register.special_needs': 'احتياجات خاصة',
    'register.send_confirm': 'إرسال تأكيد',
    'register.back_login': 'العودة لتسجيل الدخول',
    # ADMIN
    'admin.back_to_dashboard': 'العودة للوحة التحكم',
    'admin.badge_hide_preview': 'إخفاء المعاينة',
    'admin.badge_load_error': 'خطأ في تحميل إعدادات الشارة',
    'admin.badge_preview_realtime': 'معاينة الشارة في الوقت الفعلي',
    'admin.badge_save_error': 'خطأ في حفظ الشارة',
    'admin.badge_saved': 'تم حفظ الشارة',
    'admin.badge_show_preview': 'إظهار المعاينة',
    'admin.collab_add_first': 'أضف أول متعاون',
    'admin.collab_added': 'تمت إضافة المتعاون',
    'admin.collab_all_statuses': 'جميع الحالات',
    'admin.collab_all_types': 'جميع الأنواع',
    'admin.collab_belongs_to': 'ينتمي إلى',
    'admin.collab_col_company': 'الشركة',
    'admin.collab_col_contact': 'الاتصال',
    'admin.collab_col_name': 'الاسم',
    'admin.collab_col_status': 'الحالة',
    'admin.collab_col_type': 'النوع',
    'admin.collab_count': 'عدد المتعاونين',
    'admin.collab_delete_error': 'خطأ في حذف المتعاون',
    'admin.collab_deleted': 'تم حذف المتعاون',
    'admin.collab_empty': 'لا يوجد متعاونون',
    'admin.collab_exhibitors': 'العارضون',
    'admin.collab_exhibitors_sing': 'العارض',
    'admin.collab_modal_add': 'إضافة متعاون',
    'admin.collab_modal_edit': 'تعديل المتعاون',
    'admin.collab_partners': 'الشركاء',
    'admin.collab_partners_sing': 'الشريك',
    'admin.collab_search_ph': 'بحث في المتعاونين...',
    'admin.collab_stand': 'الجناح',
    'admin.collab_status_error': 'خطأ في تغيير الحالة',
    'admin.collab_subtitle': 'إدارة متعاوني العارضين والشركاء',
    'admin.collab_title': 'المتعاونون',
    'admin.collab_update_btn': 'تحديث المتعاون',
    'admin.collab_updated': 'تم تحديث المتعاون',
    'admin.config_api_error': 'خطأ في API',
    'admin.config_complete': 'الإعداد مكتمل',
    'admin.config_db_ok': 'قاعدة البيانات متصلة',
    'admin.config_field_configured': 'الحقل مُعدّ',
    'admin.config_field_required': 'الحقل مطلوب',
    'admin.config_first_use_hint': 'ابدأ بإعداد الحقول المطلوبة',
    'admin.config_first_use_title': 'الإعداد الأول',
    'admin.config_global_completion': 'الاكتمال الكلي',
    'admin.config_how_to': 'كيفية الإعداد',
    'admin.config_missing_required': 'حقول مطلوبة مفقودة',
    'admin.config_no_table': 'الجدول غير موجود',
    'admin.config_no_table_sql': 'SQL لإنشاء الجدول',
    'admin.config_nothing_to_save': 'لا شيء للحفظ',
    'admin.config_open_link': 'فتح الرابط',
    'admin.config_reg_closed': 'التسجيل مغلق',
    'admin.config_reg_control_subtitle': 'فتح/إغلاق التسجيلات',
    'admin.config_reg_control_title': 'التحكم في التسجيل',
    'admin.config_reg_exhibitors': 'تسجيلات العارضين',
    'admin.config_reg_opened': 'التسجيل مفتوح',
    'admin.config_reg_partners': 'تسجيلات الشركاء',
    'admin.config_reg_realtime': 'التسجيلات في الوقت الفعلي',
    'admin.config_required_fields': 'الحقول المطلوبة',
    'admin.config_section_saved': 'تم حفظ القسم',
    'admin.config_smtp_missing': 'SMTP مفقود',
    'admin.config_smtp_ok': 'SMTP مُعدّ',
    'admin.config_subtitle': 'إعداد المعرض والخدمات',
    'admin.config_test_db': 'اختبار قاعدة البيانات',
    'admin.config_test_email': 'اختبار البريد الإلكتروني',
    'admin.config_title': 'الإعداد',
    'admin.email_templates_active_label': 'نشط',
    'admin.email_templates_edit': 'تعديل القالب',
    'admin.email_templates_html_content': 'محتوى HTML',
    'admin.email_templates_html_ph': 'أدخل محتوى HTML...',
    'admin.email_templates_list_desc': 'إدارة قوالب البريد الإلكتروني',
    'admin.email_templates_list_title': 'قوالب البريد الإلكتروني',
    'admin.email_templates_load_error': 'خطأ في تحميل القوالب',
    'admin.email_templates_preview': 'معاينة',
    'admin.email_templates_preview_notice': 'هذه معاينة فقط',
    'admin.email_templates_save_error': 'خطأ في حفظ القالب',
    'admin.email_templates_saved': 'تم حفظ القالب',
    'admin.email_templates_see_html': 'عرض HTML',
    'admin.email_templates_see_text': 'عرض النص',
    'admin.email_templates_select_to_edit': 'اختر قالباً للتعديل',
    'admin.email_templates_subject': 'الموضوع',
    'admin.email_templates_subject_label': 'موضوع البريد',
    'admin.email_templates_subject_ph': 'أدخل موضوع البريد...',
    'admin.email_templates_subtitle': 'تخصيص قوالب البريد الإلكتروني',
    'admin.email_templates_text_content': 'محتوى نصي',
    'admin.email_templates_text_ph': 'أدخل المحتوى النصي...',
    'admin.email_templates_title': 'قوالب البريد الإلكتروني',
    'admin.event_load_error': 'خطأ في تحميل الحدث',
    'admin.event_not_found': 'الحدث غير موجود',
    'admin.exhibitor_load_error': 'خطأ في تحميل العارض',
    'admin.exhibitor_not_found': 'العارض غير موجود',
    'admin.invitations_approved': 'الدعوات المقبولة',
    'admin.invitations_load_error': 'خطأ في تحميل الدعوات',
    'admin.invitations_passport': 'جواز السفر',
    'admin.invitations_purpose': 'غرض الزيارة',
    'admin.invitations_reason': 'السبب',
    'admin.invitations_reject_ph': 'سبب الرفض...',
    'admin.invitations_reject_reason_required': 'سبب الرفض مطلوب',
    'admin.invitations_rejected': 'الدعوات المرفوضة',
    'admin.invitations_subtitle': 'إدارة طلبات الدعوات الدولية',
    'admin.invitations_title': 'الدعوات الدولية',
    'admin.live_duration': 'المدة',
    'admin.live_guest': 'الضيف',
    'admin.live_host': 'المضيف',
    'admin.live_load_error': 'خطأ في تحميل البث المباشر',
    'admin.live_messages': 'الرسائل',
    'admin.live_no_scheduled': 'لا يوجد بث مجدول',
    'admin.live_none_active': 'لا يوجد بث نشط',
    'admin.live_none_active_hint': 'لا يوجد بث نشط حالياً',
    'admin.live_on_air': 'على الهواء',
    'admin.live_scheduled': 'مجدول',
    'admin.live_start_btn': 'بدء البث',
    'admin.live_start_error': 'خطأ في بدء البث',
    'admin.live_started': 'بدأ البث',
    'admin.live_stop': 'إيقاف البث',
    'admin.live_stop_error': 'خطأ في إيقاف البث',
    'admin.live_stopped': 'توقف البث',
    'admin.live_stream_settings': 'إعدادات البث',
    'admin.live_subtitle': 'إدارة البث المباشر',
    'admin.live_title': 'البث المباشر',
    'admin.live_total_views': 'إجمالي المشاهدات',
    'admin.live_viewers': 'المشاهدون',
    'admin.media_all_processed': 'تم معالجة الكل',
    'admin.media_approval_subtitle': 'مراجعة المحتوى المقدم',
    'admin.media_approval_title': 'موافقة الوسائط',
    'admin.media_approve_error': 'خطأ في الموافقة',
    'admin.media_approved': 'تمت الموافقة',
    'admin.media_create_add_speaker': 'إضافة متحدث',
    'admin.media_create_back': 'رجوع',
    'admin.media_create_btn': 'إنشاء وسيط',
    'admin.media_create_creating': 'جارٍ الإنشاء...',
    'admin.media_create_error': 'خطأ في الإنشاء',
    'admin.media_create_no_tags': 'لا توجد وسوم',
    'admin.media_create_publish_date': 'تاريخ النشر',
    'admin.media_create_publish_status': 'حالة النشر',
    'admin.media_create_section_info': 'المعلومات الأساسية',
    'admin.media_create_section_speakers': 'المتحدثون',
    'admin.media_create_section_tags': 'الوسوم',
    'admin.media_create_section_type': 'النوع',
    'admin.media_create_section_urls': 'الروابط',
    'admin.media_create_speaker': 'المتحدث',
    'admin.media_create_subtitle': 'إضافة محتوى إعلامي جديد',
    'admin.media_create_success': 'تم إنشاء الوسيط',
    'admin.media_create_title': 'إنشاء وسيط',
    'admin.media_create_title_required': 'العنوان مطلوب',
    'admin.media_edit_back': 'رجوع',
    'admin.media_edit_desc_ph': 'وصف الوسيط...',
    'admin.media_edit_error': 'خطأ في التعديل',
    'admin.media_edit_load_error': 'خطأ في التحميل',
    'admin.media_edit_required': 'الحقل مطلوب',
    'admin.media_edit_speakers_json': 'المتحدثون (JSON)',
    'admin.media_edit_status': 'الحالة',
    'admin.media_edit_subtitle': 'تعديل المحتوى الإعلامي',
    'admin.media_edit_success': 'تم التحديث',
    'admin.media_edit_tags': 'الوسوم',
    'admin.media_edit_title': 'تعديل الوسيط',
    'admin.media_edit_title_ph': 'عنوان الوسيط...',
    'admin.media_edit_update_btn': 'تحديث',
    'admin.media_edit_updating': 'جارٍ التحديث...',
    'admin.media_lib_copied': 'تم النسخ',
    'admin.media_lib_copy_url': 'نسخ الرابط',
    'admin.media_lib_delete_error': 'خطأ في الحذف',
    'admin.media_lib_delete_irreversible': 'هذا الإجراء لا رجعة فيه',
    'admin.media_lib_delete_title': 'حذف الملف',
    'admin.media_lib_deleted': 'تم الحذف',
    'admin.media_lib_drag': 'اسحب',
    'admin.media_lib_drop': 'أفلت هنا',
    'admin.media_lib_formats': 'الصيغ المدعومة',
    'admin.media_lib_image_type': 'صورة',
    'admin.media_lib_images': 'الصور',
    'admin.media_lib_load_error': 'خطأ في التحميل',
    'admin.media_lib_no_files': 'لا توجد ملفات',
    'admin.media_lib_no_files_hint': 'ارفع أول ملف لك',
    'admin.media_lib_subtitle': 'إدارة ملفات الوسائط',
    'admin.media_lib_tags_ph': 'أضف وسوماً...',
    'admin.media_lib_title': 'مكتبة الوسائط',
    'admin.media_lib_upload_btn': 'رفع ملف',
    'admin.media_lib_upload_cat': 'الفئة',
    'admin.media_lib_upload_error': 'خطأ في الرفع',
    'admin.media_lib_uploaded': 'تم الرفع',
    'admin.media_lib_uploading': 'جارٍ الرفع...',
    'admin.media_lib_url_copied': 'تم نسخ الرابط',
    'admin.media_lib_video_type': 'فيديو',
    'admin.media_lib_videos': 'الفيديوهات',
    'admin.media_load_error': 'خطأ في التحميل',
    'admin.media_none_pending': 'لا يوجد محتوى معلق',
    'admin.media_preview': 'معاينة',
    'admin.media_reject_error': 'خطأ في الرفض',
    'admin.media_reject_reason_label': 'سبب الرفض',
    'admin.media_reject_reason_ph': 'أدخل سبب الرفض...',
    'admin.media_reject_reason_required': 'سبب الرفض مطلوب',
    'admin.media_rejected': 'تم الرفض',
    'admin.media_type': 'النوع',
    'admin.media_witness_profile': 'ملف الشاهد',
    'admin.press_add_first': 'أضف أول صحفي',
    'admin.press_add_journalist': 'إضافة صحفي',
    'admin.press_badge_auto': 'شارة تلقائية',
    'admin.press_badge_title': 'شارة الصحافة',
    'admin.press_create_badge_btn': 'إنشاء شارة',
    'admin.press_create_error': 'خطأ في الإنشاء',
    'admin.press_created': 'تم الإنشاء',
    'admin.press_delete_error': 'خطأ في الحذف',
    'admin.press_deleted': 'تم الحذف',
    'admin.press_email_col': 'البريد الإلكتروني',
    'admin.press_empty': 'لا يوجد صحفيون',
    'admin.press_load_error': 'خطأ في التحميل',
    'admin.press_media_col': 'الوسيلة الإعلامية',
    'admin.press_name_col': 'الاسم',
    'admin.press_search_ph': 'بحث في الصحفيين...',
    'admin.press_status_col': 'الحالة',
    'admin.press_subtitle': 'إدارة الصحفيين المعتمدين',
    'admin.press_title': 'الصحافة',
    'admin.press_update_error': 'خطأ في التحديث',
    'admin.press_updated': 'تم التحديث',
    'admin.analytics_trends': 'اتجاهات التحليلات',
    'admin.api_calls_24h': 'استدعاءات API (24 ساعة)',
    'admin.approved': 'موافق عليه',
    # ABOUT
    'about.badge': 'حول SIB',
    'about.card_desc': 'اكتشف ما يجعل SIB حدثاً استثنائياً',
    'about.card_title': 'معرض البناء الدولي',
    'about.countries_stat': 'دولة مشاركة',
    'about.cta_button': 'اكتشف المزيد',
    'about.cta_desc': 'انضم إلى آلاف المهنيين في قطاع البناء',
    'about.cta_title': 'كن جزءاً من SIB 2026',
    'about.days_stat': 'أيام',
    'about.desc1': 'المعرض الدولي للبناء هو الحدث المرجعي لقطاع البناء',
    'about.desc2': 'مكان التلاقي بين المهنيين والخبراء والمبتكرين',
    'about.desc3': 'فرصة فريدة للتواصل واكتشاف آخر المستجدات',
    'about.excellence': 'التميز',
    'about.excellence_desc': 'معايير عالية وجودة استثنائية',
    'about.exhibitors_stat': 'عارض',
    'about.innovation': 'الابتكار',
    'about.innovation_desc': 'أحدث التقنيات وحلول البناء',
    'about.international': 'الطابع الدولي',
    'about.international_desc': 'مشاركة دولية من جميع أنحاء العالم',
    'about.networking': 'التواصل',
    'about.networking_desc': 'بناء شراكات مهنية قيّمة',
    'about.visitors_stat': 'زائر',
    # ACCOMMODATION
    'accommodation.contact_desc': 'فريقنا متاح للمساعدة في إيجاد أفضل الأسعار',
    'accommodation.how_to_book': 'كيفية الحجز',
    'accommodation.need_help': 'تحتاج مساعدة؟',
    'accommodation.step1_desc': 'تصفح الفنادق المتاحة بالقرب من المعرض',
    'accommodation.step1_title': 'اختر الفندق',
    'accommodation.step2_desc': 'حدد تواريخ الإقامة',
    'accommodation.step2_title': 'اختر التواريخ',
    'accommodation.step3_desc': 'أدخل بياناتك وأكمل الحجز',
    'accommodation.step3_title': 'أكمل الحجز',
    'accommodation.step4_desc': 'استلم تأكيد الحجز عبر البريد الإلكتروني',
    'accommodation.step4_title': 'تأكيد الحجز',
    'accommodation.view_details': 'عرض التفاصيل',
    # ANALYTICS
    'analytics.by_type': 'حسب النوع',
    'analytics.by_sector': 'حسب القطاع',
    'analytics.by_country': 'حسب البلد',
    'analytics.by_day': 'حسب اليوم',
    'analytics.by_hour': 'حسب الساعة',
    'analytics.chart_title': 'الرسم البياني',
    'analytics.comparison': 'المقارنة',
    'analytics.conversion': 'التحويل',
    'analytics.data_period': 'فترة البيانات',
    'analytics.download_report': 'تنزيل التقرير',
    'analytics.engagement': 'التفاعل',
    'analytics.export_csv': 'تصدير CSV',
    'analytics.funnel': 'القمع',
    'analytics.growth': 'النمو',
    'analytics.insights': 'الرؤى',
    'analytics.last_30_days': 'آخر 30 يوماً',
    'analytics.last_7_days': 'آخر 7 أيام',
    'analytics.last_month': 'الشهر الماضي',
    'analytics.last_week': 'الأسبوع الماضي',
    'analytics.last_year': 'السنة الماضية',
    'analytics.load_error': 'خطأ في تحميل التحليلات',
    'analytics.no_data': 'لا توجد بيانات',
    'analytics.overview': 'نظرة عامة',
    'analytics.period': 'الفترة',
    'analytics.rate': 'المعدل',
    'analytics.realtime': 'الوقت الفعلي',
    'analytics.registrations': 'التسجيلات',
    'analytics.revenue': 'الإيراد',
    'analytics.subtitle': 'إحصائيات وتحليلات SIB',
    'analytics.this_month': 'هذا الشهر',
    'analytics.this_week': 'هذا الأسبوع',
    'analytics.this_year': 'هذه السنة',
    'analytics.title': 'التحليلات',
    'analytics.today': 'اليوم',
    'analytics.top_exhibitors': 'أبرز العارضين',
    'analytics.top_sectors': 'أبرز القطاعات',
    'analytics.traffic': 'الحركة',
    'analytics.trends': 'الاتجاهات',
    'analytics.visitors': 'الزوار',
    # BADGE
    'badge.download': 'تنزيل الشارة',
    'badge.download_pdf': 'تنزيل PDF',
    'badge.email_sent': 'تم إرسال الشارة بالبريد الإلكتروني',
    'badge.generate': 'توليد الشارة',
    'badge.load_error': 'خطأ في تحميل الشارة',
    'badge.not_found': 'الشارة غير موجودة',
    'badge.preview': 'معاينة الشارة',
    'badge.print': 'طباعة الشارة',
    'badge.qr_code': 'رمز QR',
    'badge.ready': 'الشارة جاهزة',
    'badge.save_error': 'خطأ في حفظ الشارة',
    'badge.saved': 'تم حفظ الشارة',
    'badge.scan': 'مسح الشارة',
    'badge.scanned': 'تم مسح الشارة',
    'badge.send_email': 'إرسال بالبريد الإلكتروني',
    'badge.subtitle': 'شارة المشاركة الخاصة بك',
    'badge.title': 'الشارة',
    'badge.type_exhibitor': 'شارة العارض',
    'badge.type_partner': 'شارة الشريك',
    'badge.type_press': 'شارة الصحافة',
    'badge.type_vip': 'شارة VIP',
    'badge.type_visitor': 'شارة الزائر',
    'badge.update_error': 'خطأ في التحديث',
    'badge.updated': 'تم تحديث الشارة',
    'badge.valid': 'الشارة صالحة',
    'badge.invalid': 'الشارة غير صالحة',
    # CATALOG
    'catalog.add_cart': 'أضف للسلة',
    'catalog.all_categories': 'جميع الفئات',
    'catalog.available': 'متاح',
    'catalog.cart': 'السلة',
    'catalog.cart_empty': 'السلة فارغة',
    'catalog.checkout': 'إتمام الطلب',
    'catalog.continue_shopping': 'مواصلة التسوق',
    'catalog.day': 'يوم',
    'catalog.delivery': 'التسليم',
    'catalog.description': 'الوصف',
    'catalog.details': 'التفاصيل',
    'catalog.dimensions': 'الأبعاد',
    'catalog.duration': 'المدة',
    'catalog.error': 'خطأ',
    'catalog.filter': 'تصفية',
    'catalog.image': 'الصورة',
    'catalog.in_cart': 'في السلة',
    'catalog.include': 'يشمل',
    'catalog.items': 'عناصر',
    'catalog.load_error': 'خطأ في تحميل الكتالوج',
    'catalog.name': 'الاسم',
    'catalog.not_available': 'غير متاح',
    'catalog.order_confirm': 'تأكيد الطلب',
    'catalog.order_created': 'تم إنشاء الطلب',
    'catalog.order_error': 'خطأ في الطلب',
    'catalog.per': 'لكل',
    'catalog.price': 'السعر',
    'catalog.quantity': 'الكمية',
    'catalog.remove': 'إزالة',
    'catalog.search': 'البحث في الكتالوج',
    'catalog.sort': 'ترتيب',
    'catalog.subtotal': 'المجموع الفرعي',
    'catalog.summary': 'ملخص الطلب',
    'catalog.title': 'كتالوج التأجير',
    'catalog.total': 'المجموع',
    'catalog.unit': 'الوحدة',
    'catalog.view_details': 'عرض التفاصيل',
    'catalog.weight': 'الوزن',
    # CHATBOT
    'chatbot.ask_placeholder': 'اسألني أي سؤال...',
    'chatbot.ask_sib': 'اسأل عن SIB',
    'chatbot.close': 'إغلاق',
    'chatbot.error': 'عذراً، حدث خطأ. حاول مرة أخرى.',
    'chatbot.greeting': 'مرحباً! كيف يمكنني مساعدتك؟',
    'chatbot.hello': 'مرحباً',
    'chatbot.history': 'سجل المحادثات',
    'chatbot.intro': 'أنا مساعدك الافتراضي لـ SIB 2026',
    'chatbot.minimize': 'تصغير',
    'chatbot.new_chat': 'محادثة جديدة',
    'chatbot.open': 'افتح المحادثة',
    'chatbot.send': 'إرسال',
    'chatbot.suggestions': 'اقتراحات',
    'chatbot.thinking': 'يفكر...',
    'chatbot.title': 'مساعد SIB',
    'chatbot.topics': 'المواضيع',
    'chatbot.type_message': 'اكتب رسالتك...',
    'chatbot.welcome': 'مرحباً بك في مساعد SIB',
    'chatbot.what_can_i_help': 'كيف يمكنني المساعدة؟',
    'chatbot.you': 'أنت',
    'chatbot.bot': 'المساعد',
    'chatbot.powered_by': 'مدعوم بالذكاء الاصطناعي',
    'chatbot.session_expired': 'انتهت الجلسة',
    'chatbot.retry': 'حاول مرة أخرى',
    'chatbot.copy_response': 'نسخ الرد',
    'chatbot.copied': 'تم النسخ',
    'chatbot.feedback_helpful': 'هذا مفيد',
    'chatbot.feedback_not_helpful': 'هذا غير مفيد',
    'chatbot.sources': 'المصادر',
    'chatbot.expand': 'توسيع',
    'chatbot.collapse': 'طي',
    'chatbot.language': 'اللغة',
    # CHECKOUT
    'checkout.back': 'رجوع',
    'checkout.billing': 'الفوترة',
    'checkout.cancel': 'إلغاء',
    'checkout.card_number': 'رقم البطاقة',
    'checkout.complete': 'إتمام الطلب',
    'checkout.confirm': 'تأكيد الدفع',
    'checkout.cvv': 'CVV',
    'checkout.email': 'البريد الإلكتروني',
    'checkout.error': 'خطأ في الدفع',
    'checkout.expiry': 'تاريخ الانتهاء',
    'checkout.name_on_card': 'الاسم على البطاقة',
    'checkout.order_summary': 'ملخص الطلب',
    'checkout.payment': 'الدفع',
    'checkout.payment_method': 'طريقة الدفع',
    'checkout.processing': 'جارٍ المعالجة...',
    'checkout.secure': 'دفع آمن',
    'checkout.subtotal': 'المجموع الفرعي',
    'checkout.success': 'تم الدفع بنجاح',
    'checkout.tax': 'الضريبة',
    'checkout.title': 'إتمام الطلب',
    'checkout.total': 'المجموع',
    # CHECKIN
    'checkin.access_granted': 'تم منح الوصول',
    'checkin.access_denied': 'تم رفض الوصول',
    'checkin.already_checked': 'تم التسجيل مسبقاً',
    'checkin.badge_invalid': 'الشارة غير صالحة',
    'checkin.badge_valid': 'الشارة صالحة',
    'checkin.camera_error': 'خطأ في الكاميرا',
    'checkin.confirm': 'تأكيد التسجيل',
    'checkin.error': 'خطأ في التسجيل',
    'checkin.instructions': 'امسح الشارة لتسجيل الدخول',
    'checkin.manual': 'تسجيل يدوي',
    'checkin.scan': 'مسح',
    'checkin.subtitle': 'تسجيل دخول الحضور',
    'checkin.success': 'تم تسجيل الدخول بنجاح',
    'checkin.title': 'تسجيل الدخول',
    # CONTACT
    'contact.address': 'العنوان',
    'contact.button': 'إرسال الرسالة',
    'contact.email': 'البريد الإلكتروني',
    'contact.error': 'خطأ في الإرسال',
    'contact.fax': 'الفاكس',
    'contact.form_subtitle': 'ملء النموذج وسنرد عليك في أقرب وقت',
    'contact.form_title': 'أرسل رسالة',
    'contact.hours': 'ساعات العمل',
    'contact.map': 'الخريطة',
    'contact.message': 'الرسالة',
    'contact.message_ph': 'اكتب رسالتك هنا...',
    'contact.name': 'الاسم الكامل',
    'contact.name_ph': 'أدخل اسمك',
    'contact.phone': 'الهاتف',
    'contact.sent': 'تم إرسال رسالتك',
    'contact.subject': 'الموضوع',
    'contact.subject_ph': 'موضوع رسالتك',
    'contact.subtitle': 'نحن هنا للإجابة على جميع استفساراتك',
    'contact.title': 'اتصل بنا',
    # COUNTDOWN
    'countdown.days': 'أيام',
    'countdown.hours': 'ساعات',
    'countdown.minutes': 'دقائق',
    'countdown.seconds': 'ثوانٍ',
    'countdown.title': 'العد التنازلي',
    'countdown.subtitle': 'موعد انطلاق SIB 2026',
    'countdown.until': 'حتى',
    'countdown.starts_in': 'يبدأ خلال',
    'countdown.started': 'بدأ المعرض!',
    'countdown.ended': 'انتهى المعرض',
    'countdown.happening_now': 'يجري الآن!',
    'countdown.left': 'متبقٍّ',
    'countdown.loading': 'جارٍ التحميل...',
    'countdown.error': 'خطأ في تحميل التاريخ',
    # DASHBOARD
    'dashboard.welcome': 'مرحباً',
    'dashboard.subtitle': 'لوحة التحكم الخاصة بك',
    'dashboard.total_visitors': 'إجمالي الزوار',
    'dashboard.total_exhibitors': 'إجمالي العارضين',
    'dashboard.total_partners': 'إجمالي الشركاء',
    'dashboard.registered': 'المسجلون',
    'dashboard.active': 'النشطون',
    'dashboard.pending': 'المعلقون',
    'dashboard.recent_activity': 'النشاط الأخير',
    'dashboard.quick_actions': 'إجراءات سريعة',
    'dashboard.stats': 'الإحصائيات',
    'dashboard.events_today': 'أحداث اليوم',
    'dashboard.upcoming': 'القادمة',
    'dashboard.messages': 'الرسائل',
    'dashboard.notifications': 'الإشعارات',
    'dashboard.profile_complete': 'اكتمال الملف',
    'dashboard.complete_profile': 'أكمل ملفك الشخصي',
    'dashboard.load_error': 'خطأ في التحميل',
    'dashboard.refresh': 'تحديث',
    'dashboard.export': 'تصدير',
    'dashboard.filters': 'الفلاتر',
    'dashboard.today': 'اليوم',
    'dashboard.this_week': 'هذا الأسبوع',
    'dashboard.this_month': 'هذا الشهر',
    'dashboard.all_time': 'كل الوقت',
    'dashboard.chart': 'الرسم البياني',
    'dashboard.table': 'الجدول',
    'dashboard.no_data': 'لا توجد بيانات',
    'dashboard.see_all': 'عرض الكل',
    # EVENT
    'event.all': 'جميع الأحداث',
    'event.date': 'التاريخ',
    'event.description': 'الوصف',
    'event.duration': 'المدة',
    'event.empty': 'لا توجد أحداث',
    'event.end': 'النهاية',
    'event.exhibitor': 'العارض',
    'event.filter': 'تصفية الأحداث',
    'event.full': 'ممتلئ',
    'event.keynote': 'الخطاب الرئيسي',
    'event.language': 'اللغة',
    'event.load_error': 'خطأ في تحميل الأحداث',
    'event.location': 'الموقع',
    'event.panel': 'النقاش',
    'event.program': 'البرنامج',
    'event.register': 'التسجيل',
    'event.registered': 'مسجل',
    'event.registration_closed': 'التسجيل مغلق',
    'event.registration_error': 'خطأ في التسجيل',
    'event.registration_success': 'تم التسجيل',
    'event.room': 'القاعة',
    'event.search': 'بحث في الأحداث',
    'event.seats': 'المقاعد',
    'event.seats_left': 'مقاعد متبقية',
    'event.session': 'الجلسة',
    'event.speaker': 'المتحدث',
    'event.speakers': 'المتحدثون',
    'event.start': 'البداية',
    'event.subtitle': 'برنامج SIB 2026',
    'event.title': 'الأحداث',
    'event.type': 'النوع',
    'event.upcoming': 'القادمة',
    'event.workshop': 'ورشة العمل',
    # EVENT_FORM
    'event_form.capacity': 'السعة',
    'event_form.cancel': 'إلغاء',
    'event_form.create': 'إنشاء الحدث',
    'event_form.date': 'التاريخ',
    'event_form.description': 'الوصف',
    'event_form.description_ph': 'وصف الحدث...',
    'event_form.duration': 'المدة (دقائق)',
    'event_form.end_time': 'وقت الانتهاء',
    'event_form.error': 'خطأ في الحفظ',
    'event_form.language': 'اللغة',
    'event_form.location': 'الموقع',
    'event_form.location_ph': 'موقع الحدث...',
    'event_form.modal_create': 'إنشاء حدث جديد',
    'event_form.modal_edit': 'تعديل الحدث',
    'event_form.required': 'الحقل مطلوب',
    'event_form.save': 'حفظ',
    'event_form.session': 'الجلسة',
    'event_form.speakers': 'المتحدثون',
    'event_form.speakers_ph': 'أضف متحدثين...',
    'event_form.start_time': 'وقت البداية',
    'event_form.title': 'العنوان',
    'event_form.title_ph': 'عنوان الحدث...',
    'event_form.type': 'النوع',
    'event_form.type_keynote': 'خطاب رئيسي',
    'event_form.type_panel': 'نقاش',
    'event_form.type_workshop': 'ورشة عمل',
    'event_form.type_networking': 'تواصل',
    'event_form.update': 'تحديث الحدث',
    # EXHIBITOR
    'exhibitor.about': 'عن العارض',
    'exhibitor.activities': 'الأنشطة',
    'exhibitor.back': 'العودة للعارضين',
    'exhibitor.booth': 'الجناح',
    'exhibitor.catalog': 'الكتالوج',
    'exhibitor.certifications': 'الشهادات',
    'exhibitor.company_size': 'حجم الشركة',
    'exhibitor.contact': 'اتصل بالعارض',
    'exhibitor.description': 'الوصف',
    'exhibitor.email': 'البريد الإلكتروني',
    'exhibitor.empty': 'لا يوجد عارضون',
    'exhibitor.favorites': 'المفضلة',
    'exhibitor.filter': 'تصفية العارضين',
    'exhibitor.founded': 'تأسست سنة',
    'exhibitor.hall': 'القاعة',
    'exhibitor.load_error': 'خطأ في التحميل',
    'exhibitor.location': 'الموقع',
    'exhibitor.logo': 'الشعار',
    'exhibitor.meetings': 'الاجتماعات',
    'exhibitor.name': 'الاسم',
    'exhibitor.not_found': 'العارض غير موجود',
    'exhibitor.phone': 'الهاتف',
    'exhibitor.products': 'المنتجات',
    'exhibitor.profile': 'ملف العارض',
    'exhibitor.schedule_meeting': 'جدولة اجتماع',
    'exhibitor.search': 'بحث في العارضين',
    'exhibitor.sector': 'القطاع',
    'exhibitor.sectors': 'القطاعات',
    'exhibitor.social': 'الشبكات الاجتماعية',
    'exhibitor.stand': 'الجناح',
    'exhibitor.subtitle': 'العارضون في SIB 2026',
    'exhibitor.title': 'العارضون',
    'exhibitor.view_profile': 'عرض الملف',
    'exhibitor.website': 'الموقع الإلكتروني',
    # FOOTER
    'footer.all_rights': 'جميع الحقوق محفوظة',
    'footer.contact': 'اتصل بنا',
    'footer.copyright': 'حقوق النشر',
    'footer.follow_us': 'تابعونا',
    'footer.legal': 'قانوني',
    'footer.links': 'روابط سريعة',
    'footer.newsletter': 'النشرة الإخبارية',
    'footer.newsletter_placeholder': 'أدخل بريدك الإلكتروني...',
    'footer.newsletter_subscribe': 'اشتراك',
    'footer.privacy': 'الخصوصية',
    'footer.terms': 'الشروط',
    # HALLMAP
    'hallmap.booth': 'الجناح',
    'hallmap.direction': 'التوجيه',
    'hallmap.exhibitor': 'العارض',
    'hallmap.filter': 'تصفية',
    'hallmap.floor': 'الطابق',
    'hallmap.fullscreen': 'ملء الشاشة',
    'hallmap.hall': 'القاعة',
    'hallmap.legend': 'المفتاح',
    'hallmap.load_error': 'خطأ في تحميل الخريطة',
    'hallmap.locate_exhibitor': 'تحديد موقع العارض',
    'hallmap.map': 'خريطة المعرض',
    'hallmap.navigate': 'التنقل',
    'hallmap.plan': 'مخطط القاعة',
    'hallmap.reset': 'إعادة تعيين',
    'hallmap.search': 'بحث في الخريطة',
    'hallmap.sector': 'القطاع',
    'hallmap.subtitle': 'تصفح مخطط المعرض',
    'hallmap.title': 'خريطة المعرض',
    'hallmap.zoom_in': 'تكبير',
    'hallmap.zoom_out': 'تصغير',
    'hallmap.zones': 'المناطق',
    # HOME
    'home.badge': 'SIB 2026',
    'home.cta': 'اكتشف المزيد',
    'home.cta_exhibitor': 'أصبح عارضاً',
    'home.cta_visitor': 'سجل كزائر',
    'home.cta_partner': 'أصبح شريكاً',
    'home.desc': 'المعرض الدولي للبناء 2026',
    'home.discover': 'اكتشف',
    'home.exhibitors_count': 'عارض',
    'home.features': 'المميزات',
    'home.hero_subtitle': 'الحدث المرجعي لقطاع البناء',
    'home.hero_title': 'معرض البناء الدولي 2026',
    'home.join': 'انضم',
    'home.latest_news': 'آخر الأخبار',
    'home.partners': 'الشركاء',
    'home.program': 'البرنامج',
    'home.register': 'التسجيل',
    'home.see_all': 'عرض الكل',
    'home.sponsors': 'الرعاة',
    'home.stats': 'الإحصائيات',
    'home.subtitle': 'بناء المستقبل معاً',
    'home.title': 'الرئيسية',
    'home.venue': 'مكان الانعقاد',
    'home.visitors_count': 'زائر',
    'home.welcome': 'مرحباً بك في SIB',
    # INVITATION
    'invitation.accept': 'قبول الدعوة',
    'invitation.accepted': 'تم قبول الدعوة',
    'invitation.cancel': 'إلغاء',
    'invitation.code': 'رمز الدعوة',
    'invitation.code_invalid': 'رمز الدعوة غير صالح',
    'invitation.confirm': 'تأكيد',
    'invitation.declined': 'تم رفض الدعوة',
    'invitation.email': 'البريد الإلكتروني',
    'invitation.error': 'خطأ في الدعوة',
    'invitation.expire': 'انتهاء الصلاحية',
    'invitation.expired': 'انتهت صلاحية الدعوة',
    'invitation.from': 'من',
    'invitation.invalid': 'الدعوة غير صالحة',
    'invitation.message': 'الرسالة',
    'invitation.name': 'الاسم',
    'invitation.pending': 'قيد الانتظار',
    'invitation.resend': 'إعادة إرسال الدعوة',
    'invitation.send': 'إرسال دعوة',
    'invitation.sent': 'تم إرسال الدعوة',
    'invitation.subtitle': 'تفاصيل الدعوة',
    'invitation.title': 'الدعوة',
    'invitation.to': 'إلى',
    'invitation.type': 'نوع الدعوة',
    # METRICS
    'metrics.avg': 'المتوسط',
    'metrics.avg_session': 'متوسط الجلسة',
    'metrics.badges_scanned': 'الشارات الممسوحة',
    'metrics.bounced': 'معدل الارتداد',
    'metrics.conversion_rate': 'معدل التحويل',
    'metrics.daily': 'يومياً',
    'metrics.data_period': 'فترة البيانات',
    'metrics.engaged': 'المتفاعلون',
    'metrics.load_error': 'خطأ في تحميل المقاييس',
    'metrics.max': 'الحد الأقصى',
    'metrics.meetings_held': 'الاجتماعات المنعقدة',
    'metrics.min': 'الحد الأدنى',
    'metrics.monthly': 'شهرياً',
    'metrics.new_registrations': 'التسجيلات الجديدة',
    'metrics.no_data': 'لا توجد بيانات',
    'metrics.overview': 'نظرة عامة',
    'metrics.page_views': 'مشاهدات الصفحة',
    'metrics.peak': 'الذروة',
    'metrics.period': 'الفترة',
    'metrics.realtime': 'الوقت الفعلي',
    'metrics.sessions': 'الجلسات',
    'metrics.subtitle': 'مقاييس الأداء',
    'metrics.title': 'المقاييس',
    'metrics.total': 'المجموع',
    'metrics.trend': 'الاتجاه',
    'metrics.unique_visitors': 'الزوار الفريدون',
    'metrics.weekly': 'أسبوعياً',
    # MINISITE
    'minisite.about': 'عن الشركة',
    'minisite.contact': 'اتصل بنا',
    'minisite.description': 'الوصف',
    'minisite.edit': 'تعديل',
    'minisite.email': 'البريد الإلكتروني',
    'minisite.error': 'خطأ',
    'minisite.gallery': 'المعرض',
    'minisite.hero': 'الصورة الرئيسية',
    'minisite.keywords': 'الكلمات المفتاحية',
    'minisite.load_error': 'خطأ في التحميل',
    'minisite.logo': 'الشعار',
    'minisite.name': 'الاسم',
    'minisite.not_found': 'الموقع غير موجود',
    'minisite.phone': 'الهاتف',
    'minisite.preview': 'معاينة',
    'minisite.products': 'المنتجات',
    'minisite.publish': 'نشر',
    'minisite.published': 'منشور',
    'minisite.save': 'حفظ',
    'minisite.save_error': 'خطأ في الحفظ',
    'minisite.saved': 'تم الحفظ',
    'minisite.sector': 'القطاع',
    'minisite.share': 'مشاركة',
    'minisite.social': 'الشبكات الاجتماعية',
    'minisite.subtitle': 'موقع العارض المصغر',
    'minisite.title': 'الموقع المصغر',
    'minisite.unpublish': 'إلغاء النشر',
    'minisite.website': 'الموقع الإلكتروني',
    # MODERATION
    'moderation.approve': 'موافقة',
    'moderation.approve_error': 'خطأ في الموافقة',
    'moderation.approved': 'تمت الموافقة',
    'moderation.content': 'المحتوى',
    'moderation.empty': 'لا يوجد محتوى للمراجعة',
    'moderation.load_error': 'خطأ في التحميل',
    'moderation.pending': 'قيد المراجعة',
    'moderation.reason': 'السبب',
    'moderation.reject': 'رفض',
    'moderation.reject_error': 'خطأ في الرفض',
    'moderation.rejected': 'تم الرفض',
    'moderation.subtitle': 'مراجعة المحتوى المقدم',
    'moderation.title': 'الإشراف على المحتوى',
    'moderation.type': 'النوع',
    'moderation.user': 'المستخدم',
    # NETWORKING
    'networking.appointments': 'المواعيد',
    'networking.available': 'متاح',
    'networking.bio': 'السيرة الذاتية',
    'networking.book_meeting': 'احجز اجتماعاً',
    'networking.cancel_meeting': 'إلغاء الاجتماع',
    'networking.company': 'الشركة',
    'networking.connect': 'التواصل',
    'networking.connections': 'الاتصالات',
    'networking.contacts': 'جهات الاتصال',
    'networking.discover': 'اكتشف',
    'networking.email': 'البريد الإلكتروني',
    'networking.empty': 'لا توجد اتصالات',
    'networking.filter': 'تصفية',
    'networking.interests': 'الاهتمامات',
    'networking.load_error': 'خطأ في التحميل',
    'networking.match_score': 'نقاط التوافق',
    'networking.meeting_accepted': 'تم قبول الاجتماع',
    'networking.meeting_cancelled': 'تم إلغاء الاجتماع',
    'networking.meeting_declined': 'تم رفض الاجتماع',
    'networking.meeting_pending': 'الاجتماع قيد الانتظار',
    'networking.meeting_request': 'طلب اجتماع',
    'networking.meeting_scheduled': 'الاجتماع مجدول',
    'networking.meetings': 'الاجتماعات',
    'networking.message': 'رسالة',
    'networking.name': 'الاسم',
    'networking.no_matches': 'لا يوجد توافق',
    'networking.phone': 'الهاتف',
    'networking.position': 'المنصب',
    'networking.profile': 'الملف',
    'networking.recommend': 'موصى به',
    'networking.request_sent': 'تم إرسال الطلب',
    'networking.schedule': 'جدولة',
    'networking.search': 'بحث',
    'networking.sector': 'القطاع',
    'networking.send_message': 'إرسال رسالة',
    'networking.subtitle': 'شبكة العلاقات المهنية',
    'networking.title': 'التواصل',
    'networking.view_profile': 'عرض الملف',
    # NEWS
    'news.all': 'جميع الأخبار',
    'news.author': 'الكاتب',
    'news.back': 'العودة',
    'news.category': 'الفئة',
    'news.date': 'التاريخ',
    'news.empty': 'لا توجد أخبار',
    'news.error': 'خطأ في تحميل الأخبار',
    'news.featured': 'الأخبار المميزة',
    'news.latest': 'آخر الأخبار',
    'news.load_error': 'خطأ في التحميل',
    'news.no_results': 'لا توجد نتائج',
    'news.read_more': 'اقرأ المزيد',
    'news.related': 'ذات صلة',
    'news.search': 'بحث في الأخبار',
    'news.share': 'مشاركة',
    'news.subtitle': 'آخر أخبار SIB',
    'news.tags': 'الوسوم',
    'news.title': 'الأخبار',
    # NEWS_FORM
    'news_form.cancel': 'إلغاء',
    'news_form.category': 'الفئة',
    'news_form.content': 'المحتوى',
    'news_form.content_ph': 'محتوى المقال...',
    'news_form.create': 'إنشاء مقال',
    'news_form.date': 'التاريخ',
    'news_form.edit': 'تعديل المقال',
    'news_form.error': 'خطأ في الحفظ',
    'news_form.image': 'الصورة',
    'news_form.image_url': 'رابط الصورة',
    'news_form.required': 'الحقل مطلوب',
    'news_form.save': 'حفظ',
    'news_form.status': 'الحالة',
    'news_form.subtitle': 'الوصف التفصيلي',
    'news_form.subtitle_ph': 'ملخص المقال...',
    'news_form.tags': 'الوسوم',
    'news_form.tags_ph': 'أضف وسوماً...',
    'news_form.title': 'العنوان',
    'news_form.title_ph': 'عنوان المقال...',
    'news_form.update': 'تحديث',
    # PARTNER
    'partner.activities': 'الأنشطة',
    'partner.add': 'إضافة شريك',
    'partner.all': 'جميع الشركاء',
    'partner.badge': 'الشارة',
    'partner.back': 'العودة',
    'partner.bio': 'نبذة',
    'partner.cancel': 'إلغاء',
    'partner.certifications': 'الشهادات',
    'partner.company': 'الشركة',
    'partner.contact': 'اتصل بالشريك',
    'partner.create': 'إنشاء شريك',
    'partner.dashboard': 'لوحة التحكم',
    'partner.delete': 'حذف',
    'partner.description': 'الوصف',
    'partner.details': 'التفاصيل',
    'partner.edit': 'تعديل',
    'partner.email': 'البريد الإلكتروني',
    'partner.empty': 'لا يوجد شركاء',
    'partner.error': 'خطأ',
    'partner.events': 'الأحداث',
    'partner.filter': 'تصفية',
    'partner.founded': 'تأسست سنة',
    'partner.id': 'المعرّف',
    'partner.industries': 'القطاعات',
    'partner.level': 'المستوى',
    'partner.list': 'قائمة الشركاء',
    'partner.load_error': 'خطأ في التحميل',
    'partner.logo': 'الشعار',
    'partner.meetings': 'الاجتماعات',
    'partner.name': 'الاسم',
    'partner.not_found': 'الشريك غير موجود',
    'partner.offers': 'العروض',
    'partner.phone': 'الهاتف',
    'partner.plan': 'الخطة',
    'partner.profile': 'الملف',
    'partner.promote': 'ترويج',
    'partner.resources': 'الموارد',
    'partner.save': 'حفظ',
    'partner.save_error': 'خطأ في الحفظ',
    'partner.saved': 'تم الحفظ',
    'partner.schedule_meeting': 'جدولة اجتماع',
    'partner.search': 'بحث في الشركاء',
    'partner.sector': 'القطاع',
    'partner.services': 'الخدمات',
    'partner.size': 'الحجم',
    'partner.social': 'الشبكات الاجتماعية',
    'partner.status': 'الحالة',
    'partner.subscription': 'الاشتراك',
    'partner.subtitle': 'شركاء SIB 2026',
    'partner.title': 'الشركاء',
    'partner.type': 'النوع',
    'partner.update': 'تحديث',
    'partner.view_profile': 'عرض الملف',
    'partner.visibility': 'الظهور',
    'partner.website': 'الموقع الإلكتروني',
    'partner.year': 'السنة',
    # PAYMENT
    'payment.amount': 'المبلغ',
    'payment.cancel': 'إلغاء',
    'payment.card': 'البطاقة',
    'payment.confirm': 'تأكيد الدفع',
    'payment.currency': 'العملة',
    'payment.date': 'التاريخ',
    'payment.description': 'الوصف',
    'payment.details': 'تفاصيل الدفع',
    'payment.email': 'البريد الإلكتروني',
    'payment.error': 'خطأ في الدفع',
    'payment.expired': 'منتهي الصلاحية',
    'payment.failed': 'فشل الدفع',
    'payment.history': 'سجل المدفوعات',
    'payment.invoice': 'الفاتورة',
    'payment.load_error': 'خطأ في التحميل',
    'payment.method': 'طريقة الدفع',
    'payment.name': 'الاسم',
    'payment.no_history': 'لا يوجد سجل دفع',
    'payment.order': 'الطلب',
    'payment.paid': 'مدفوع',
    'payment.pay': 'دفع',
    'payment.pending': 'قيد الانتظار',
    'payment.process': 'معالجة الدفع',
    'payment.processing': 'جارٍ المعالجة...',
    'payment.receipt': 'الإيصال',
    'payment.refund': 'استرداد',
    'payment.refunded': 'تم الاسترداد',
    'payment.status': 'حالة الدفع',
    'payment.subtitle': 'إدارة المدفوعات',
    'payment.success': 'تم الدفع بنجاح',
    'payment.tax': 'الضريبة',
    'payment.title': 'الدفع',
    'payment.total': 'المجموع',
    'payment.transaction': 'المعاملة',
    'payment.type': 'النوع',
    # PRESS
    'press.accreditation': 'الاعتماد',
    'press.badge': 'شارة الصحافة',
    'press.contact': 'اتصل',
    'press.credentials': 'الوثائق',
    'press.download_kit': 'تنزيل مجموعة الصحافة',
    'press.email': 'البريد الإلكتروني',
    'press.empty': 'لا يوجد صحفيون',
    'press.filter': 'تصفية',
    'press.journalist': 'الصحفي',
    'press.kit': 'مجموعة الصحافة',
    'press.load_error': 'خطأ في التحميل',
    'press.media_name': 'الوسيلة الإعلامية',
    'press.name': 'الاسم',
    'press.phone': 'الهاتف',
    'press.register': 'تسجيل كصحفي',
    'press.search': 'بحث في الصحفيين',
    'press.subtitle': 'موارد الصحافة',
    'press.title': 'الصحافة',
    # PRODUCTS
    'products.add': 'إضافة منتج',
    'products.category': 'الفئة',
    'products.create': 'إنشاء منتج',
    'products.delete': 'حذف',
    'products.delete_error': 'خطأ في الحذف',
    'products.deleted': 'تم الحذف',
    'products.description': 'الوصف',
    'products.edit': 'تعديل',
    'products.empty': 'لا توجد منتجات',
    'products.error': 'خطأ',
    'products.filter': 'تصفية',
    'products.image': 'الصورة',
    'products.load_error': 'خطأ في التحميل',
    'products.name': 'اسم المنتج',
    'products.not_found': 'المنتج غير موجود',
    'products.price': 'السعر',
    'products.published': 'منشور',
    'products.save': 'حفظ',
    'products.save_error': 'خطأ في الحفظ',
    'products.saved': 'تم الحفظ',
    'products.search': 'بحث في المنتجات',
    'products.sector': 'القطاع',
    'products.status': 'الحالة',
    'products.subtitle': 'إدارة المنتجات',
    'products.title': 'المنتجات',
    'products.type': 'النوع',
    'products.unpublished': 'غير منشور',
    'products.update': 'تحديث',
    'products.update_error': 'خطأ في التحديث',
    'products.updated': 'تم التحديث',
    'products.view': 'عرض',
    # RENTAL
    'rental.back': 'رجوع',
    'rental.cancel': 'إلغاء',
    'rental.catalog': 'كتالوج التأجير',
    'rental.confirm': 'تأكيد الطلب',
    'rental.contract': 'العقد',
    'rental.days': 'أيام',
    'rental.details': 'تفاصيل الطلب',
    'rental.duration': 'المدة',
    'rental.empty': 'لا توجد عناصر',
    'rental.end_date': 'تاريخ الانتهاء',
    'rental.equipment': 'المعدة',
    'rental.error': 'خطأ في الطلب',
    'rental.load_error': 'خطأ في التحميل',
    'rental.order': 'طلب الإيجار',
    'rental.payment': 'الدفع',
    'rental.price': 'السعر',
    'rental.quantity': 'الكمية',
    'rental.start_date': 'تاريخ البداية',
    'rental.status': 'الحالة',
    'rental.submit': 'إرسال الطلب',
    'rental.success': 'تم الطلب بنجاح',
    'rental.summary': 'ملخص الطلب',
    'rental.title': 'تأجير المعدات',
    'rental.total': 'المجموع',
    'rental.type': 'النوع',
    'rental.unit': 'الوحدة',
    # SATISFACTION
    'satisfaction.comment': 'تعليق',
    'satisfaction.comment_ph': 'شاركنا رأيك...',
    'satisfaction.error': 'خطأ في الإرسال',
    'satisfaction.excellent': 'ممتاز',
    'satisfaction.good': 'جيد',
    'satisfaction.improvement': 'يحتاج تحسين',
    'satisfaction.message': 'شكراً على ملاحظاتك',
    'satisfaction.poor': 'ضعيف',
    'satisfaction.question': 'ما رأيك في تجربتك؟',
    'satisfaction.rating': 'التقييم',
    'satisfaction.send': 'إرسال',
    'satisfaction.sent': 'تم الإرسال',
    'satisfaction.skip': 'تخطي',
    'satisfaction.subtitle': 'نقدر ملاحظاتك',
    'satisfaction.survey': 'استطلاع الرضا',
    'satisfaction.title': 'الرضا',
    'satisfaction.very_good': 'جيد جداً',
    'satisfaction.very_poor': 'ضعيف جداً',
    # SCANS
    'scans.badge': 'الشارة',
    'scans.cancel': 'إلغاء',
    'scans.checkin': 'تسجيل الدخول',
    'scans.count': 'عدد المسوحات',
    'scans.date': 'التاريخ',
    'scans.empty': 'لا توجد مسوحات',
    'scans.error': 'خطأ في المسح',
    'scans.export': 'تصدير',
    'scans.filter': 'تصفية',
    'scans.history': 'سجل المسوحات',
    'scans.load_error': 'خطأ في التحميل',
    'scans.location': 'الموقع',
    'scans.manual': 'يدوي',
    'scans.name': 'الاسم',
    'scans.scanner': 'الماسح',
    'scans.search': 'بحث',
    'scans.start': 'بدء المسح',
    'scans.status': 'الحالة',
    'scans.subtitle': 'سجل مسوحات الشارات',
    'scans.time': 'الوقت',
    'scans.title': 'المسوحات',
    'scans.today': 'مسوحات اليوم',
    'scans.total': 'المجموع',
    'scans.type': 'النوع',
    # SESSION_REG
    'session_reg.already_registered': 'أنت مسجل بالفعل',
    'session_reg.cancel': 'إلغاء التسجيل',
    'session_reg.cancel_error': 'خطأ في إلغاء التسجيل',
    'session_reg.cancelled': 'تم إلغاء التسجيل',
    'session_reg.confirm': 'تأكيد التسجيل',
    'session_reg.error': 'خطأ في التسجيل',
    'session_reg.full': 'الجلسة ممتلئة',
    'session_reg.register': 'التسجيل في الجلسة',
    'session_reg.registered': 'مسجل في الجلسة',
    'session_reg.registration_closed': 'التسجيل مغلق',
    'session_reg.seats': 'المقاعد المتبقية',
    'session_reg.session': 'الجلسة',
    'session_reg.speakers': 'المتحدثون',
    'session_reg.subtitle': 'التسجيل في الجلسة',
    'session_reg.success': 'تم التسجيل بنجاح',
    'session_reg.time': 'الوقت',
    'session_reg.title': 'تسجيل الجلسة',
    'session_reg.type': 'النوع',
    'session_reg.waitlist': 'قائمة الانتظار',
    'session_reg.waitlisted': 'أنت في قائمة الانتظار',
    # TEAM
    'team.add': 'إضافة عضو',
    'team.bio': 'السيرة الذاتية',
    'team.cancel': 'إلغاء',
    'team.company': 'الشركة',
    'team.create': 'إنشاء عضو',
    'team.delete': 'حذف',
    'team.delete_error': 'خطأ في الحذف',
    'team.deleted': 'تم الحذف',
    'team.department': 'القسم',
    'team.edit': 'تعديل',
    'team.email': 'البريد الإلكتروني',
    'team.empty': 'لا يوجد أعضاء',
    'team.error': 'خطأ',
    'team.filter': 'تصفية',
    'team.image': 'الصورة',
    'team.linkedin': 'LinkedIn',
    'team.load_error': 'خطأ في التحميل',
    'team.name': 'الاسم',
    'team.phone': 'الهاتف',
    'team.position': 'المنصب',
    'team.role': 'الدور',
    'team.save': 'حفظ',
    'team.save_error': 'خطأ في الحفظ',
    'team.saved': 'تم الحفظ',
    'team.search': 'بحث في الفريق',
    'team.subtitle': 'فريق SIB',
    'team.title': 'الفريق',
    'team.twitter': 'Twitter',
    'team.type': 'النوع',
    'team.update': 'تحديث',
    'team.update_error': 'خطأ في التحديث',
    'team.updated': 'تم التحديث',
    # TRANSFER
    'transfer.amount': 'المبلغ',
    'transfer.cancel': 'إلغاء',
    'transfer.confirm': 'تأكيد النقل',
    'transfer.date': 'التاريخ',
    'transfer.description': 'الوصف',
    'transfer.email': 'البريد الإلكتروني',
    'transfer.error': 'خطأ في النقل',
    'transfer.from': 'من',
    'transfer.history': 'سجل النقل',
    'transfer.load_error': 'خطأ في التحميل',
    'transfer.name': 'الاسم',
    'transfer.no_history': 'لا يوجد سجل نقل',
    'transfer.reference': 'المرجع',
    'transfer.send': 'إرسال',
    'transfer.sent': 'تم الإرسال',
    'transfer.status': 'الحالة',
    'transfer.subtitle': 'نقل الطلبات',
    'transfer.success': 'تم النقل بنجاح',
    'transfer.title': 'النقل',
    'transfer.to': 'إلى',
    'transfer.type': 'النوع',
    # VISITOR_SETTINGS
    'visitor_settings.accessibility': 'إمكانية الوصول',
    'visitor_settings.cancel': 'إلغاء',
    'visitor_settings.categories': 'الفئات',
    'visitor_settings.communications': 'الاتصالات',
    'visitor_settings.company': 'الشركة',
    'visitor_settings.email': 'البريد الإلكتروني',
    'visitor_settings.firstname': 'الاسم الأول',
    'visitor_settings.interests': 'الاهتمامات',
    'visitor_settings.language': 'اللغة',
    'visitor_settings.lastname': 'اسم العائلة',
    'visitor_settings.load_error': 'خطأ في التحميل',
    'visitor_settings.networking': 'التواصل',
    'visitor_settings.newsletter': 'النشرة الإخبارية',
    'visitor_settings.notifications': 'الإشعارات',
    'visitor_settings.phone': 'الهاتف',
    'visitor_settings.position': 'المنصب',
    'visitor_settings.privacy': 'الخصوصية',
    'visitor_settings.profile': 'الملف الشخصي',
    'visitor_settings.receive_news': 'استقبال الأخبار',
    'visitor_settings.save': 'حفظ',
    'visitor_settings.save_error': 'خطأ في الحفظ',
    'visitor_settings.saved': 'تم الحفظ',
    'visitor_settings.search': 'البحث',
    'visitor_settings.sectors': 'القطاعات',
    'visitor_settings.show_profile': 'إظهار الملف',
    'visitor_settings.subtitle': 'إعدادات الزائر',
    'visitor_settings.title': 'الإعدادات',
    'visitor_settings.update_error': 'خطأ في التحديث',
    'visitor_settings.visibility': 'الظهور',
    # SECTEURS
    'secteurs.title_1': 'قطاعات',
    'secteurs.title_2': 'النشاط',
    # SPEAKERS
    'speakers.bio': 'السيرة الذاتية',
    'speakers.company': 'الشركة',
    'speakers.empty': 'لا يوجد متحدثون',
    'speakers.filter': 'تصفية',
    'speakers.load_error': 'خطأ في التحميل',
    'speakers.name': 'الاسم',
    'speakers.position': 'المنصب',
    'speakers.search': 'بحث في المتحدثين',
    'speakers.sessions': 'الجلسات',
    'speakers.social': 'الشبكات الاجتماعية',
    'speakers.subtitle': 'متحدثو SIB 2026',
    'speakers.title': 'المتحدثون',
    # PRESENTATION
    'presentation.title': 'تقديم SIB',
    'presentation.subtitle': 'المعرض الدولي للبناء',
    # ERRORS
    'errors.not_found': 'الصفحة غير موجودة',
    'errors.server': 'خطأ في الخادم',
    'errors.unauthorized': 'غير مصرح',
    'errors.forbidden': 'محظور',
    'errors.network': 'خطأ في الشبكة',
    'errors.timeout': 'انتهى وقت الاتصال',
    'errors.unknown': 'خطأ غير معروف',
    'errors.retry': 'حاول مرة أخرى',
    'errors.back_home': 'العودة للرئيسية',
}

# ─────────────────────────────────────────────────────────────────────────────
# Appliquer les corrections dans translations.ts
# ─────────────────────────────────────────────────────────────────────────────
content = open('src/store/translations.ts', encoding='utf-8').read()

import re

# Trouver le bloc ar
ar_start = re.search(r'\n  ar:\s*\{', content)
ar_end_match = re.search(r'\n  es:\s*\{', content)

if not ar_start or not ar_end_match:
    print("ERREUR: Impossible de trouver les blocs ar/es")
    exit()

ar_block_start = ar_start.end()
ar_block_end = ar_end_match.start()

ar_block = content[ar_block_start:ar_block_end]

# Remplacer chaque clé non-arabe par sa traduction
fixed = 0
not_in_dict = []

for key, ar_value in AR.items():
    # Pattern: 'key': 'valeur_quelconque' dans le bloc ar
    pattern = r"('" + re.escape(key) + r"'\s*:\s*')([^']*?)(')"
    replacement = r'\g<1>' + ar_value.replace('\\', '\\\\') + r'\3'
    
    new_ar_block, count = re.subn(pattern, replacement, ar_block)
    if count > 0:
        ar_block = new_ar_block
        fixed += count

# Reconstruire le contenu
content = content[:ar_block_start] + ar_block + content[ar_block_end:]

# Sauvegarder
open('src/store/translations.ts', 'w', encoding='utf-8').write(content)
print(f"Clés corrigées: {fixed}")
print("Terminé!")

# Vérification
content2 = open('src/store/translations.ts', encoding='utf-8').read()
ar_m = re.search(r'\n  ar:\s*\{(.+?)\n  \},?\s*\n\s*es:', content2, re.DOTALL)
if ar_m:
    ar_b = ar_m.group(1)
    keys2 = re.findall(r"'([^']+)'\s*:\s*'([^']*)'", ar_b)
    total2 = len(keys2)
    good2 = sum(1 for k, v in keys2 if any('\u0600' <= c <= '\u06ff' for c in v))
    print(f"\nRésultat: {good2}/{total2} clés AR avec texte arabe ({100*good2//total2}%)")
